Changing "Significant" to "Notable" in GA blog template (Staging)
OpenLiberty/blogs pull request #1317
Opened 2021-04-10 08:56 UTC by jakub-pomykala

2021-04-12 13:39 UTC, mbroz2 requested changes

2021-04-12 13:39 UTC, mbroz2 commented on templates/ga-release-post.adoc
> +// For this section ask either Tom Evens, Michal Broz or the #openliberty-release-blog channel for Notable bug fixes in this release.
Should be Tom Evans (@tevans78 )

2021-04-14 16:18 UTC, jakub-pomykala commented on templates/ga-release-post.adoc
> +// For this section ask either Tom Evens, Michal Broz or the #openliberty-release-blog channel for Notable bug fixes in this release.
Done

2021-04-14 18:39 UTC, mbroz2 approved these changes

2021-04-15 20:59 UTC, merged