OL stack gradle support blog
OpenLiberty/blogs pull request #1640
Opened 2021-08-18 21:47 UTC by mezarin

Associated with issue: #1611 
Link to Built draft post: https://draft-openlibertyio.mybluemix.net/blog/2021/08/30/open-liberty-stack-gradle.html

2021-08-18 21:54 UTC, scottkurz approved these changes, later dismissed
Looks like I approved this already so LGTM

2021-08-30 21:19 UTC, dmuelle requested changes
Great post- clear and to the point. I made a few suggestions for concision and clarity. Note that compound adjectives such as "Gradle-built" or "Maven-based" should use a hyphen. There are quite a few in this post so might want to rephrase a couple to avoid having a ton of hyphens throughout. Feel free to ping me with any questions- thanks

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +title: "Cloud-native Development of Gradle Built Applications with the Open Liberty Devfile Stack"
for all three title instances- title should use sentence-style capitalization rather than headline style, and Gradle-built needs a hyphen:

Cloud-native development of Gradle-built applications with the Open Liberty devfile stack

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +The Open Liberty devfile stack now allows you build and deploy new and existing cloud-native applications using Gradle. The stack leverages link:https://github.com/OpenLiberty/ci.gradle[Open Liberty
Gradle-built applications

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +The link:https://github.com/OpenLiberty/application-stack#open-liberty-application-stack[Open Liberty devfile stack] provides much of the infrastructure (Open Liberty, Maven/Gradle, Open J9, etc.) ne
suggested edit:

These images are used by the devfiles provided by the stack to serve as the base for building and running your applications. 
--->
The devfiles that are provided by the stack use these images as a base to build and run your applications.

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +
might be helpful to define what a devfile is in a sentence or two here and link to https://docs.devfile.io/ (if that's the right link)

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +The Open Liberty devfile stack provides two fully configured link:https://docs.devfile.io/devfile/2.1.0/user-guide/index.html[devfiles]: A link:https://github.com/devfile/registry/blob/main/stacks/ja
suggested edit

These devfiles will allow you to deploy your Maven or Gradle built applications with ease as these devfiles define the environment and set of steps needed to build and deploy your application using the Open Liberty runtime.

--->

These devfiles define the environment and steps to build and deploy your application using the Open Liberty runtime.

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +link:https://odo.dev[Odo] is a simple CLI tool that you use to create devfile based components that interact directly with your Kubernetes cluster to setup the environment, and build/deploy/access/de
suugested edit:

[Odo] is a simple CLI tool that you use to create devfile based components that interact directly with your Kubernetes cluster to setup the environment, and build/deploy/access/debug your application.

--->

[Odo] is a simple CLI tool to create devfile-based components that interact directly with your Kubernetes cluster. These components set up the environment, and also build, deploy, access, and debug your application.

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +- Openshift Do. If you have not already installed odo, do so now by following the instructions outlined in the link:https://odo.dev[odo] documentation.
link:https://odo.dev[odo] documentation.
--->
link:https://odo.dev[odo documentation].

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +- An application using Gradle. You can use your own application, or use one of the stack provided applications such as the link:https://github.com/OpenLiberty/application-stack-intro[intro] or link:h
the stack provided applications such as
--->
the stack-provided applications, such as...
or
the applications provided by the stack, such as...
or 
the stack applications, such as

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +- An application using Gradle. You can use your own application, or use one of the stack provided applications such as the link:https://github.com/OpenLiberty/application-stack-intro[intro] or link:h
suggested edit:
Instruction on how to use the starter application can be found link:https://github.com/OpenLiberty/application-stack/wiki/Using-the-Default-Starter#getting-started[here]
--->
For instructions on how to use the starter application, see link:https://github.com/OpenLiberty/application-stack/wiki/Using-the-Default-Starter#getting-started[Using the Default Starter: Getting started].

Also, I would move this sentence to be the last sentence of this paragraph, after "For this blog, we will use the intro application. This is a basic application that uses JAX-RS and MicroProfile technologies."

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +Clone the application.
Clone the application
--->
First, clone the intro application

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +That is all. The application is now deployed on your cluster, and a URL has been made available to access the application.
suggested edit:
The application is now deployed on your cluster, and a URL has been made available to access the application. 
--->
The application is now deployed on your cluster and a URL is available to access it.

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +Now, let's see if the application was deployed successfully. For this, we need to get the URL to access the application.
suggested edit 

For this, we need to get the URL to access the application.

--->

We can get the URL to access the application by running `odo url list`:

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +To access the REST endpoint for the application, append `/api/resource` to the URL listed in the previous step (i.e. `http://ep1-my-ol-component-my-project.my.kube.cluster.ibm.com/api/resource`) and
suggested edit:

To access the REST endpoint for the application, append `/api/resource` to the URL listed in the previous step (i.e. `http://ep1-my-ol-component-my-project.my.kube.cluster.ibm.com/api/resource`) and access it through a browser or through the command line.

--->

To access the REST endpoint for the application, append `/api/resource` to the URL listed in the previous step, for example, `http://ep1-my-ol-component-my-project.my.kube.cluster.ibm.com/api/resource`. You can access this endpoint through a browser or by running a `curl` command:

2021-08-30 21:19 UTC, dmuelle commented on posts/2021-08-30-open-liberty-stack-gradle.adoc
> +
would be helpful to add a sentence or two as an overview of what the post will cover. Something like, "In this post, we'll use the Open Liberty devfile stack and Openshift do to deploy a sample application to a Kubernetes cluster"

2021-09-01 17:27 UTC, dmuelle approved these changes

2021-09-01 17:28 UTC, merged