Create fast-setup-of-a-java-microservice.adoc
OpenLiberty/blogs pull request #166
Opened 2019-10-21 09:04 UTC by yasmin-aumeeruddy

2019-10-22 13:47 UTC, lauracowen requested changes
Somehow this .adoc file has ended up in the `img/blog` folder. Can you move it into `drafts`?

2019-10-23 13:10 UTC, yasmin-aumeeruddy commented
https://github.com/OpenLiberty/blogs/pull/166/commits/a6083d9dd794322f7c93578a7d9744799063cfce

I made a new commit

2019-11-15 15:19 UTC, lauracowen requested changes
- [x] Can you make syntax changes as described in https://github.ibm.com/Engagement-Demos/Developer-Engagement/issues/24?
- [x] Make "MicroProfileStarter" two words throughout (ie "MicroProfile Starter")
- [x] There's a typo in the main heading.
Thx

2020-01-29 10:57 UTC, lauracowen approved these changes

2020-01-29 10:57 UTC, merged