Phillyjug blog
OpenLiberty/blogs pull request #1794
Opened 2021-10-08 14:45 UTC by ajm01

2021-10-21 15:02 UTC, dmuelle requested changes
ID Review- great post! I just made a few suggestions to break up the "wall of text" a  bit and make a couple sentences more concise and readable. Let me know if you have any questions- thanks!

2021-10-21 15:02 UTC, dmuelle commented on posts/2021-10-05-openliberty-jug-presentation.adoc
> +open-graph-image: https://openliberty.io/img/twitter_card.jpg
for visibility in social media previews, replace the twitter card with the image from the post:

https://openliberty.io/img/blog/cupofjoe.png

2021-10-21 15:02 UTC, dmuelle commented on posts/2021-10-05-openliberty-jug-presentation.adoc
> +As the popularity of a microservice architecture and cloud-native application development experience grows, it is an exciting time to talk about the Open Liberty framework's support of those. I recen
recommend starting with the second sentence- it makes a more direct connection. You could either move the first sentence to the end of the paragraph, or omit it.

2021-10-21 15:02 UTC, dmuelle commented on posts/2021-10-05-openliberty-jug-presentation.adoc
> +The focus of the presentation centered around Open Liberty as an open framework for Java developers that highly optimizes the development of microservices using Eclipse MicroProfile and Jakarta EE AP
a couple suggestions here-

for concision and clarity:
The focus of the presentation centered around Open Liberty as an open framework for Java developers that highly optimizes the development of microservices using Eclipse MicroProfile and Jakarta EE APIs
--->
The presentation focused  how Open Liberty highly optimizes the development of microservices by using Eclipse MicroProfile and Jakarta EE APIs

The sentence that follows is really long and a bit hard to parse- what are the design attributes and what are the descriptions of those attributes- they all kind of jumble together. Consider breaking this sentence up, shortening it, or converting to a bulleted list.

2021-10-21 15:02 UTC, dmuelle commented on posts/2021-10-05-openliberty-jug-presentation.adoc
> +The second half of the Open Liberty overview detailed its rich developer experience thru Open Liberty's support of rapid development using a tight inner-loop experience provided by the Liberty Maven
is it possible to combine the description of the demo with the list of links? For each link you could move the part of the paragraph that follows it, eg.

https://youtu.be/qvoEhgw90Ig[Demo 1 - Developing locally with Open Liberty's dev mode]:: 
By demonstrating a Java RESTful application being enhanced locally in an IDE, the participants were able to see the quick turnaround time developers can achieve using the https://openliberty.io/docs/21.0.0.10/development-mode.html[dev mode] feature of the Liberty Maven Plugin.

If you use the description list syntax show above (double colon :: after the term, description on the following line) it should apply a nice heading style to the links and nest the descriptions neatly beneath.

also might be good to include a link to [the Open Liberty Maven plugin](https://github.com/OpenLiberty/ci.maven) on first mention in this section

2021-10-21 15:02 UTC, dmuelle commented on posts/2021-10-05-openliberty-jug-presentation.adoc
> +The Philadelphia JUG meetup presentation was well attended with 35+ attendees joining via the meetup's web conferencing tool. The host of the meetup was excited to have the group listen to the streng
for concision and clarity:

The host of the meetup was excited to have the group listen to the strengths of Open Liberty and its developer's experience and I was happy to have had the opportunity to speak with this group about the exiting attributes of Open Liberty.
--->
The host of the meetup was excited for the group to hear about the strengths of Open Liberty and its developer experience, and I was happy for the opportunity to speak with them.

2021-10-22 21:13 UTC, ajm01 commented on posts/2021-10-05-openliberty-jug-presentation.adoc
> +The second half of the Open Liberty overview detailed its rich developer experience thru Open Liberty's support of rapid development using a tight inner-loop experience provided by the Liberty Maven
I couldn't get the '::' to work - i used a '+' to include paragraph text under the given bullet point.

2021-10-25 14:01 UTC, dmuelle approved these changes

2021-10-25 14:02 UTC, merged