Sbo blog update draft
OpenLiberty/blogs pull request #1814
Opened 2021-10-13 14:55 UTC by mezarin

Thsi PR removes Service Binding Operator mentions. This was triggered by ODO's temporary removal (ODO 2.4.0) of the support for linking applications and services using the Service Binding Operator. ODO has its own application/service linking capability based on SBO APIs; therefore, for the time being, this is what this blog will showcase.

2021-10-13 15:18 UTC, scottkurz requested changes

2021-10-13 15:18 UTC, scottkurz commented on posts/2021-09-17-binding-app-to-postgresql-db-with-odo-and-ol-stack.adoc
> +In this post, we’ll use the Open Liberty devfile stack and Openshift odo to easily deploy an application that uses the Java Persistence API (JPA) and bind a PostgreSQL database to the application.
Openshift => OpenShift

2021-10-13 15:18 UTC, scottkurz commented on posts/2021-09-17-binding-app-to-postgresql-db-with-odo-and-ol-stack.adoc
> +Adding the annotations ensures that odo will inject the `databaseName`, `databasePassword` and `databaseUser` spec values into the application. Note that the instance name you configure will be used
I think we need to at least make a nod to the fact that there's a mapping happening under the covers...before by SBO, now by odo itself, to get to  server.xml vars like:
`${DATABASE_DB_USER}`

2021-10-13 16:44 UTC, scottkurz commented on posts/2021-09-17-binding-app-to-postgresql-db-with-odo-and-ol-stack.adoc
> +The instance name you configure will be used as part of the name of various artifacts and resource references. Be sure to change it.
OK.. I was confused.. I see what you're saying.

How about: 
> Be sure to change the metadata name from the generated value to 'sampledatabase' in order to match the instructions below.

2021-10-13 16:44 UTC, scottkurz submitted a review, later dismissed
Suggested change.

2021-10-14 15:47 UTC, mezarin commented on posts/2021-09-17-binding-app-to-postgresql-db-with-odo-and-ol-stack.adoc
> +The instance name you configure will be used as part of the name of various artifacts and resource references. Be sure to change it.
done

2021-10-14 15:47 UTC, mezarin commented on posts/2021-09-17-binding-app-to-postgresql-db-with-odo-and-ol-stack.adoc
> +In this post, we’ll use the Open Liberty devfile stack and Openshift odo to easily deploy an application that uses the Java Persistence API (JPA) and bind a PostgreSQL database to the application.
done

2021-10-14 15:50 UTC, mezarin commented
Hi @dmuelle, it looks like the draft branch has not caught up with the prod branch. Could you please sync those two branches before this PR is merged. Thanks!.

2021-10-14 16:17 UTC, dmuelle commented
> Hi @dmuelle, it looks like the draft branch has not caught up with the prod branch. Could you please sync those two branches before this PR is merged. Thanks!.

resolved the conflict, should be clear now

2021-10-14 16:21 UTC, dmuelle approved these changes
LGTM- the blog tag commits are ok now that the conflict is resovled

2021-10-14 17:00 UTC, merged