STAGING - 21.0.0.11 Release Blog
OpenLiberty/blogs pull request #1849
Opened 2021-10-27 11:04 UTC by ryan-storey

Blog draft: https://blogs-draft-openlibertyio.mybluemix.net/blog/2021/10/29/ga-release-post.html

2021-10-27 12:33 UTC, mbroz2 approved these changes

2021-10-27 12:36 UTC, epj submitted a review, later dismissed
Looks good relating to my PRs.

2021-10-27 12:50 UTC, Azquelt submitted a review, later dismissed

2021-10-27 13:00 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +       <version>21.0.0.7</version>
@bensonlatibm @jjiwooLim I take it that this version is the 'version of the user feature' and could be anything, like `1.0` correct?  Aka, there's no correlation to Liberty's version?

2021-10-27 13:01 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +       <version>21.0.0.7</version>
@bensonlatibm @jjiwooLim I take it that this version is the 'version of the user feature' and could be anything, like `1.0` correct?  Aka, there's no correlation to Liberty's version?

2021-10-27 13:01 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +    featuresBom 'userTest.user.test.features:features-bom:19.0.0.8'
@bensonlatibm @jjiwooLim I take it that this version is the 'version of the user feature' and could be anything, like `1.0` correct?  Aka, there's no correlation to Liberty's version?

2021-10-27 13:01 UTC, acdemyers submitted a review, later dismissed

2021-10-27 13:02 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +|Maven Plugin| `install-feature`with features-bom dependency
```suggestion
|Maven Plugin| `install-feature` with features-bom dependency 
```

2021-10-27 13:09 UTC, mbroz2 requested changes

2021-10-27 13:09 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +Install the user feature using the `featureUtility` command line tool, Liberty Maven or Gradle plugin. Provide the maven coordinate of the custom made `features-bom` file.
make `featureUtility` link to https://openliberty.io/docs/latest/reference/command/featureUtility-installFeature.html

2021-10-27 13:09 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +|featureUtility | `featureUtility installFeature testesa1 --featuresBom=userTest.user.test.features:features-bom:19.0.0.8`
make `featureUtility` link to https://openliberty.io/docs/latest/reference/command/featureUtility-installFeature.html

2021-10-27 13:09 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +This issue has now been resolved, meaning that the `gRPC` services should start as expected and no `FFDC`s should be logged.
```suggestion
This issue has now been resolved, meaning that the `gRPC` services should start as expected and no `FFDC` should be logged.
```

2021-10-27 13:50 UTC, pmd1nh commented on posts/2021-10-29-ga-release-post.adoc
> +    // { MyInterfaceImpl.class, MyInterface.class }
// current Liberty will pass in:
// { MyInterfaceImpl.class }
// {MyInterface} should NOT be passed into onStartup

2021-10-27 15:20 UTC, kgibm submitted a review, later dismissed

2021-10-27 15:54 UTC, jjiwooLim commented on posts/2021-10-29-ga-release-post.adoc
> +       <version>21.0.0.7</version>
It could be any version, and technically it does not have to match the version of the user feautre or Liberty. For the example above, the version is same as the Liberty version, but it could be something like `1.0`. Users need to make sure they have the user feature in the corresponding maven repo (local directory). Also, the version of `features-bom` needs to match the version of the user feature that they use. 

For ex) 
If their user features is in [userTest.user.test.features:features:21.0.0.7]
/.m2/userTest/user/test/features/testesa1/21.0.0.7/testesa1-21.0.0.7.esa
Then the features-bom file needs to be [userTest.user.test.features:features-bom:21.0.0.7]
/.m2/userTest/user/test/features/features-bom/21.0.0.7/features-bom-21.0.0.7.pom

Or it could also be 
[userTest.user.test.features:features:1.0] = /.m2/userTest/user/test/features/testesa1/1.0/testesa1-1.0.esa
 [userTest.user.test.features:features-bom:1.0] = /.m2/userTest/user/test/features/features-bom/1.0/features-bom-1.0.pom

2021-10-27 16:03 UTC, jjiwooLim commented on posts/2021-10-29-ga-release-post.adoc
> +       <version>21.0.0.7</version>
pls see the previous comment

2021-10-27 16:03 UTC, jjiwooLim commented on posts/2021-10-29-ga-release-post.adoc
> +    featuresBom 'userTest.user.test.features:features-bom:19.0.0.8'
pls see the previous comment

2021-10-27 16:20 UTC, brenthdaniel submitted a review, later dismissed

2021-10-27 17:34 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +       <version>21.0.0.7</version>
I think it would be clearer if for these examples we went with a version of `1.0` to make it clear that this is completely unrelated to the Liberty version

2021-10-27 17:34 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> + <version>21.0.0.7</version>
```suggestion
 <version>1.0</version>
```

2021-10-27 17:35 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +       <version>21.0.0.7</version>
```suggestion
       <version>1.0</version>
```

2021-10-27 17:35 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +       <version>21.0.0.7</version>
```suggestion
       <version>1.0</version>
```

2021-10-27 17:35 UTC, mbroz2 commented on posts/2021-10-29-ga-release-post.adoc
> +    featuresBom 'userTest.user.test.features:features-bom:19.0.0.8'
```suggestion
    featuresBom 'userTest.user.test.features:features-bom:1.0'
```

2021-10-27 18:29 UTC, volosied submitted a review, later dismissed
EL bug description looks good.

2021-10-27 22:41 UTC, jjiwooLim submitted a review, later dismissed

2021-10-28 14:27 UTC, mbroz2 commented
Looks good on draft:
![image](https://user-images.githubusercontent.com/3076261/139276449-28d7f957-1184-49ce-add4-31ed28c71f0b.png)

2021-10-28 14:27 UTC, mbroz2 approved these changes

2021-10-28 14:27 UTC, merged