Creating Billy meet our open source champions blog
OpenLiberty/blogs pull request #2066
Opened 2022-03-04 11:54 UTC by BillyD73

Initial blog creation

2022-03-07 18:58 UTC, dmuelle requested changes
ID review: great post- I left a few minor suggestions. Let me know if you have any questions. Thanks!

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +title: "Meet our open-source champions: Billy Dawson"
need to remove colons from the metadata field values- they cause the doc to fail. You can replace with a dash instead

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +seo-title: Meet our open-source champions: Billy Dawson
remove colon

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> += Meet our open-source champions: Billy Dawson
colon here is ok

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +open-graph-image: https://openliberty.io/img/twitter_card.jpg
replace with an image from the post in the form

https://openliberty.io/img/blog/image-file.png

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +seo-description: DESCRIPTION
replace with text from line 54 (no links) or similar summary

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +blog_description: "DESCRIPTION"
replace with text from line 54 (no links) or similar summary

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +My primary responsibility is to work on the release and development of our https://marketplace.eclipse.org/content/ibm-liberty-developer-tools[developer tools] for Liberty and WebSphere. The tools en
suggested edit:

 A significant portion of our code base has been open sourced and can be found https://github.com/OpenLiberty/open-liberty-tools[here].
--->
 A significant portion of our code base has been open sourced and can be found in the https://github.com/OpenLiberty/open-liberty-tools[open-liberty-tools GitHub repository].

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +As part of the Wasdev team – the focus of which was mostly external and community based - I fixed and improved the performance of a webpage used for quickly identifying Liberty repositories, updated
suggested edit:
As part of the Wasdev team – the focus of which was mostly external and community based - I fixed and improved the performance of a webpage used for quickly identifying Liberty repositories, updated the web site and posted the monthly Liberty release updates for beta and GA releases and built an app to analyse traffic to the main Wasdev site.

--->

As part of the Wasdev team, which is mostly external focused and community based, I fixed and improved the performance of a webpage used for quickly identifying Liberty repositories, updated the web site and posted the monthly Liberty release updates for beta and GA releases. I also built an app to analyse traffic to the main Wasdev site.

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Moreover, my placement year allowed me to enjoy a multitude of “give back” activities in addition to my day-to-day responsibilities. I attended a cross-site hackathon in Portsmouth and the University
suggested edit:

I demonstrated the Liberty Car - an RC car with the radio controller replaced with a Raspberry Pi and using IBM Cloud to allow anyone at the conference to control the car via their mobile phone - at a WebSphere User Group and the Devoxx conferences in London.

--->

At a WebSphere User Group and the Devoxx conferences in London, I demonstrated the Liberty Car , which was an RC car with the radio controller replaced with a Raspberry Pi and using IBM Cloud to allow anyone at the conference to control the car with their mobile phone.

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Such an array of experiences helped tremendously with my last year of university – I learnt so many new technologies and deepened my knowledge of key areas featured within my course. This gave me a b
suggested edit:

This gave me a brilliant foundation for my final year and having experienced the application of technology from the perspective of enterprise I better understood the application of what I was studying rather than seeing it primarily from a theoretical perspective.
--->
This gave me a brilliant foundation for my final year.  and having experienced the application of technology from the perspective of enterprise, I better understood I was studying rather than seeing it primarily from a theoretical perspective.

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Perhaps even more impactful were the soft skills I developed – my placement year significantly improved my overall confidence and communication skills. Confidence is something that I have personally
suggested edit:

Perhaps even more impactful were the soft skills I developed. My placement year significantly improved my overall confidence and communication skills.

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +I think all of this was enough to have me champing at the bit to return as a graduate, but to extend on that – I met the most amazing people on my placement and that was my primary reason for being s
recommend breaking up longer sentences

I think all of this was enough to have me champing at the bit to return as a graduate. But to extend on that, I met the most amazing people on my placement and that was my primary reason for being so keen to return. Of course, working with top talent presents the opportunity to learn an incredible amount, but I was somewhat surprised by the sheer approachability and kindness shown by these people. There were no stupid questions and despite worrying I would be taking up valuable time or distracting people from more important work, I experienced nothing but hospitality and respect.

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Furthermore, there is a great social culture at IBM – as part of my internship we were encouraged to network with our peers which resulted in regular meet up activities such as a monthly pub quiz. Ou
Furthermore, there is a great social culture at IBM . As part of my internship we were encouraged to network with our peers which resulted in regular meet up activities such as a monthly pub quiz.

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Whilst COVID has impacted this somewhat the Hursley site is an incredible place to work. It is situated on over 100 acres of rural land in Hampshire. I utilised the beautiful surroundings to go for w
There are site-wide events here, too, some of which are open to the public. For example, there is the annual Hurfest event, annual fireworks, a recent archeological dig and it was my pleasure to attend the http://ukkubb.org[2021 UK Kubb Championship] here.

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +There’s a wealth of additional activities one can participate in at IBM. I am the Hursley focal for developer advocacy which involves me planning and organising events, most frequently to reach out t
There have been several areas of technology I was particularly interested in - namely Quantum, AI and hacking. Despite not being part of my typical teamwork I was able to attend education sessions on Quantum and on hacking as well as an entire Coursera course on AI, which led to me being part of an AI work group to apply this technology to help automate workloads within the department.

2022-03-07 18:58 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Though this has not occurred thus far, I have no doubt that my involvement in open source software will open up new opportunities in the future. It has certainly impacted my work, though, as it provi
add comma

I found when working with OSS, with the knowledge that what I am contributing is public and (somewhat) irreversible, it’s excellent practice to brush up on Git skills and be extremely diligent when submitting code.

2022-03-10 16:24 UTC, BillyD73 commented
Hi @dmuelle thank you very much for the review. I've added the suggested changes to this PR

2022-03-10 18:50 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +My primary responsibility is to work on the release and development of our https://marketplace.eclipse.org/content/ibm-liberty-developer-tools[developer tools] for Liberty and WebSphere. The tools en
looks like this one and the next couple were missed, prob because they were "hidden"

2022-03-10 18:50 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +As part of the Wasdev team – the focus of which was mostly external and community based - I fixed and improved the performance of a webpage used for quickly identifying Liberty repositories, updated
this one

2022-03-10 18:51 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Moreover, my placement year allowed me to enjoy a multitude of “give back” activities in addition to my day-to-day responsibilities. I attended a cross-site hackathon in Portsmouth and the University
this one

2022-03-10 18:51 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Such an array of experiences helped tremendously with my last year of university – I learnt so many new technologies and deepened my knowledge of key areas featured within my course. This gave me a b
this one

2022-03-10 18:51 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +Perhaps even more impactful were the soft skills I developed – my placement year significantly improved my overall confidence and communication skills. Confidence is something that I have personally
this one

2022-03-10 18:51 UTC, dmuelle commented on posts/2022-03-18-BillyDawson_MeetTheTeam.adoc
> +I think all of this was enough to have me champing at the bit to return as a graduate, but to extend on that – I met the most amazing people on my placement and that was my primary reason for being s
this one

2022-03-10 18:56 UTC, dmuelle commented
Hi @BillyD73 - i think you might have missed a few comments.

2022-03-11 13:39 UTC, BillyD73 commented
@dmuelle Apologies, I hadn't noticed the hidden comments - those should be rectified now.

2022-03-14 14:19 UTC, dmuelle approved these changes
LGTM, thanks

2022-03-14 14:19 UTC, merged