First draft GA blog
OpenLiberty/blogs pull request #2078
Opened 2022-03-11 16:32 UTC by ryan-storey

2022-03-11 16:49 UTC, mbroz2 requested changes

2022-03-11 16:49 UTC, mbroz2 commented on posts/2022-03-15-ga-release-post.adoc
> +View the list of fixed bugs in link:https://github.com/OpenLiberty/open-liberty/issues?q=label%3Arelease%3A22.0.0.3_NO_PERIODS+label%3A%22release+bug%22[22.0.0.3].
Fix link

2022-03-11 16:49 UTC, mbroz2 commented on posts/2022-03-15-ga-release-post.adoc
> +We’ve spent some time fixing bugs. The following sections describe just some of the issues resolved in this release. If you’re interested, here’s the  link:https://github.com/OpenLiberty/open-liberty
Fix link

2022-03-11 16:49 UTC, mbroz2 commented on posts/2022-03-15-ga-release-post.adoc
> +For more information on the storing or Transaction Recovery Logs in an `RDBMS`, please refer to the Knowledge Center article link:https://www.ibm.com/support/pages/websphere-application-server-storin
```suggestion
  For more information on the storing or Transaction Recovery Logs in an `RDBMS`, please refer to link:https://openliberty.io/docs/22.0.0.2/transaction-service.html#log[Transaction log management] doc.
```

2022-03-11 16:49 UTC, mbroz2 commented on posts/2022-03-15-ga-release-post.adoc
> +seo-description: Open Liberty 22.0.0.3 allows SQL Operations to be retried in transaction recovery logs. This release also includes several significant bug fixes. In addition, since 22.0.0.2 we have
```suggestion
seo-description: Open Liberty 22.0.0.3 allows SQL Operations to be retried in transaction recovery logs. This release also includes several significant bug fixes. In addition, we have published a brand new Open Liberty guide on containerizing microservices with Podman!
```

2022-03-11 16:49 UTC, mbroz2 commented on posts/2022-03-15-ga-release-post.adoc
> +blog_description: Open Liberty 22.0.0.3 allows SQL Operations to be retried in transaction recovery logs. This release also includes several significant bug fixes. In addition, since 22.0.0.2 we have
```suggestion
blog_description: Open Liberty 22.0.0.3 allows SQL Operations to be retried in transaction recovery logs. This release also includes several significant bug fixes. In addition, we have published a brand new Open Liberty guide on containerizing microservices with Podman!
```

2022-03-11 16:49 UTC, mbroz2 commented on posts/2022-03-15-ga-release-post.adoc
> +Open Liberty 22.0.0.3 allows SQL Operations to be retried in transaction recovery logs. This release also includes several significant bug fixes. In addition, since 22.0.0.2 we have published a brand
```suggestion
Open Liberty 22.0.0.3 allows SQL Operations to be retried in transaction recovery logs. This release also includes several significant bug fixes. In addition, we have published a brand new Open Liberty guide on containerizing microservices with Podman!
```

2022-03-14 13:50 UTC, dmuelle reviewed
ID review- made a few suggestions, lmk if you have any questions. Thanks

2022-03-14 13:50 UTC, dmuelle commented on posts/2022-03-15-ga-release-post.adoc
> +For more information on the storing or Transaction Recovery Logs in an `RDBMS`, please refer to link:https://openliberty.io/docs/22.0.0.2/transaction-service.html#log[Transaction log management] doc.
use `latest` in the docs link unless you are targeting a specific version:

link:https://openliberty.io/docs/latest/transaction-service.html#log[Transaction log management]
or use relative URL
link:{url-prefix}/docs/latest/transaction-service.html#log[Transaction log management]

2022-03-14 13:50 UTC, dmuelle commented on posts/2022-03-15-ga-release-post.adoc
> +In Liberty, transaction services are implicitly activated when you specify features that require the use of transactions; for example, `jpa-2.0`, `jdbc-4.0`, and `wasJmsServer-1.0`.
suggested edit:

In Liberty, transaction services are implicitly activated when you specify features that use transactions, such as  `jpa-2.0`, `jdbc-4.0`, and `wasJmsServer-1.0`.

2022-03-14 13:50 UTC, dmuelle commented on posts/2022-03-15-ga-release-post.adoc
> +When Liberty detects a failure in writing to its transaction recovery logs, it will invalidate the logs and disallow further global transactions. In order to do further transactional work, the custom
suggested edit:

When Liberty detects a failure to write to its transaction recovery logs, it invalidates the logs and disallows further global transactions. To resume transactional work, you have to restart the server and reload any applications, which can take considerable time in some cases.

2022-03-14 13:50 UTC, dmuelle commented on posts/2022-03-15-ga-release-post.adoc
> +A new transaction service configuration attribute has been introduced to the transaction stanza in the Liberty `server.xml` file that allows these transaction log SQL operations to be retried. It is
A new  attribute is available for the `transaction` configuration element in the Liberty `server.xml` file that enables these transaction log SQL operations to be retried.

2022-03-14 13:50 UTC, dmuelle commented on posts/2022-03-15-ga-release-post.adoc
> +Add the feature to the `server.xml`:
should this be here? Looks like somethings missing

2022-03-14 13:50 UTC, dmuelle commented on posts/2022-03-15-ga-release-post.adoc
> +Previously, when receiving a state parameter from the RP it appears Liberty returned the state double encoded. The issue appears to occur when processing the liberty page to authorize the RP:
spell out "relying party (RP)" on first mention

2022-03-14 15:21 UTC, mbroz2 commented on posts/2022-03-15-ga-release-post.adoc
> +Add the feature to the `server.xml`:
```suggestion
```

2022-03-14 15:22 UTC, mbroz2 commented on posts/2022-03-15-ga-release-post.adoc
> +When Liberty detects a failure in writing to its transaction recovery logs, it will invalidate the logs and disallow further global transactions. In order to do further transactional work, the custom
```suggestion
When Liberty detects a failure to write to its transaction recovery logs, it invalidates the logs and disallows further global transactions. To resume transactional work, you have to restart the server and reload any applications, which can take considerable time in some cases.
```

2022-03-14 15:22 UTC, mbroz2 approved these changes

2022-03-14 15:22 UTC, merged