2111 cloud native liberty buildpack
OpenLiberty/blogs pull request #2122
Opened 2022-03-25 12:30 UTC by kevin-ortega

2022-03-25 17:42 UTC, kevin-ortega commented
![image](https://user-images.githubusercontent.com/29545669/160173653-733f8910-d10f-4c71-9569-2a502d79996a.png)

2022-03-25 17:43 UTC, kevin-ortega commented
https://draft-openlibertyio.mybluemix.net/2022/03/25/2022-03-31-cloud-native-liberty-buildpack.html

2022-03-25 19:04 UTC, dmuelle requested changes
ID review- made a few suggestions, let me know if you have any questions. Thanks!

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +---
there is some kind of problem with this metadata section but I can't tell exactly what it is. If you look at the GitHub file view, the section does not format to be a table as expected. Also, your github pic and link aren't working, nor is hankl showing up as an author, despite all the URLs being correct

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +blog_description: Use Paketo Buildpacks to easily build your apps and keep them updated.  Buildpacks transform your application
blog description value needs to be enclosed in quotes

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +blog_description: Use Paketo Buildpacks to easily build your apps and keep them updated.  Buildpacks transform your application
also, only need one space after "keep them updated."

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +seo-title: Introducing a new method to deploy your cloud native application to any cloud - paketo.io
normally this field ends with "openliberty.io" Im not sure if that's part of the problem

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +link:https://paketo.io/[Paketo buildpacks] transform your application source code into container images and easily keeps them updated.
suggested edit:
link:https://paketo.io/[Paketo buildpacks] transform your application source code into container images and easily keep those images updated.

this is correct but a little awkward (buildpacks...keep)

you could also rephrase  to something like

link:https://paketo.io/[Paketo buildpacks] transform your application source code into easily maintained container images.

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +The Paketo Cloud Native Liberty buildpack provides the Open Liberty runtime to a workflow that produces an OCI image that can run just about anywhere.
```suggestion
The link:https://github.com/paketo-buildpacks/liberty[Paketo Cloud Native Liberty buildpack] provides the Open Liberty runtime to a workflow that produces an Open Container Initiative (OCI) image that can run just about anywhere.
```

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +
recommend removing the spaces between lines

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +Download the sample getting started app:
```suggestion
Download the Open Liberty starter app:
```

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +Download the sample getting started app:
Is this example using the OL starter app as "your application source". If so, there should be some kind of explanation- the prereq list suggests they should supply their own source. Or does the starter integrate with the user source app?

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +== You can build from an on-prem Open Liberty installation
```suggestion
== Build your app from an on-prem Open Liberty installation
```

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +Using a Liberty packaged server
```suggestion
You can build from an on-prem Open Liberty installation by using a packaged Liberty server. Run the following command to package your server.
```

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +The packaged server can then be supplied to the build using the `--path` argument:
```suggestion
You can then supply the packaged server to the build by using the `--path` argument:
```

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +Or to build from a Liberty server installation, change your working directory to the installation root containing the wlp directory and run:
```suggestion
Alternatively, you can build from a Liberty server installation by changing your working directory to the installation root that contains the `wlp` directory and running the following command:
```

2022-03-25 19:04 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +Your application now is ready to run.
is it now in an OCI image that can run anywhere? If so, we should say, if not, what other steps are needed?

2022-03-25 19:37 UTC, kevin-ortega commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +blog_description: Use Paketo Buildpacks to easily build your apps and keep them updated.  Buildpacks transform your application
I made these edits.

2022-03-25 19:40 UTC, kevin-ortega commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +link:https://paketo.io/[Paketo buildpacks] transform your application source code into container images and easily keeps them updated.
Thanks, I've made this edit.

2022-03-25 19:41 UTC, kevin-ortega commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +seo-title: Introducing a new method to deploy your cloud native application to any cloud - paketo.io
I've made this edit.

2022-03-25 19:42 UTC, kevin-ortega commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +
done

2022-03-25 19:44 UTC, kevin-ortega commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +Your application now is ready to run.
Yes, it's now an OCI image.   I reworded that sentence.

2022-03-25 20:33 UTC, dmuelle requested changes
fixing the metadata and a few more minor things

2022-03-25 20:33 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +link:https://paketo.io/[Paketo buildpacks] transform your application source code into container images and easily keeps them updated.
```suggestion
link:https://paketo.io/[Paketo buildpacks] transform your application source code into container images and easily keep them updated.  
```

2022-03-25 20:33 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +Your application now is ready to run.
```suggestion
Your application is now transformed into an OCI image that is ready to run almost anywhere. 
```

2022-03-25 20:33 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +
```suggestion
The following examples use the link:/blog/2021/08/20/open-liberty-starter.html[Open Liberty starter] app as the application source.
```

2022-03-25 20:33 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +blog_description: "Use Paketo Buildpacks to easily build your apps and keep them updated. Buildpacks transform your application"
```suggestion
blog_description: "Use Paketo Buildpacks to easily build your apps and keep them updated. Buildpacks transform your application source code into container images without creating a Dockerfile!" 
```

2022-03-25 20:33 UTC, dmuelle commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +source code into container images without creating a Dockerfile!
```suggestion
```

2022-03-25 20:45 UTC, kevin-ortega commented on posts/2022-04-01-cloud-native-liberty-buildpack.adoc
> +---
I think this is resolved.

2022-03-25 20:50 UTC, kevin-ortega commented
@dmuelle Thank you for your help with the metadata problem and all your great suggested edits.

2022-03-28 13:27 UTC, dmuelle submitted a review, later dismissed

2022-03-28 13:30 UTC, dmuelle approved these changes, later dismissed

2022-03-28 15:49 UTC, dmuelle approved these changes
LGTM- just need to commit this change back to draft as well

2022-03-28 19:20 UTC, kevin-ortega commented
> 

This was actually changed in draft first...so it's already there.

2022-03-31 13:33 UTC, merged