Minor edits and front matter updates
OpenLiberty/blogs pull request #2187
Opened 2022-04-07 18:39 UTC by yeekangc

2022-04-07 18:47 UTC, dmuelle requested changes
a couple minor suggestions

2022-04-07 18:47 UTC, dmuelle commented on posts/2022-04-12-guides-updated-mp5-jakartaee9.adoc
> +seo-description: Learn how to develop cloud-native Java applications and microservices on Open Liberty with MicroProfile 5.0 and Jakarta EE 9.1 APIs using cloud-hosted guides on the openliberty.io we
```suggestion
seo-description: Learn how to develop cloud-native Java applications and microservices on Open Liberty with MicroProfile 5.0 and Jakarta EE 9.1 APIs by using cloud-hosted guides on the openliberty.io website.
```

2022-04-07 18:47 UTC, dmuelle commented on posts/2022-04-12-guides-updated-mp5-jakartaee9.adoc
> +The cloud-hosted guides are enhanced with a new look and updated features. Whether or not you've tried them yet, now is the time to experience how easy you can learn to build applications with MicroP
```suggestion
The cloud-hosted guides are enhanced with a new look and updated features. Whether or not you've tried them yet, now is the time to experience how easily you can learn to build applications with MicroProfile and Jakarta EE APIs.
```

2022-04-07 18:49 UTC, dmuelle reviewed
just realized if we commit these changes to `draft`  from a patch, they will not be in Gilbert's working branch (`gkwn-ibm-2168`) when he opens a PR to staging

2022-04-07 18:50 UTC, dmuelle commented
one option might be to rebase this PR to target `gkwn-ibm-2168` and then PR the changes to draft from that branch. There might be other workarounds though

2022-04-08 15:33 UTC, gkwan-ibm commented
Mark this PR as invalid and close it because the branch created from the draft that is no good for production.

2022-04-08 15:33 UTC, closed without merging