create bmarwell 3rd party user feature post
OpenLiberty/blogs pull request #2518
Opened 2022-08-30 17:18 UTC by dmuelle

#2336

2022-08-30 17:20 UTC, dmuelle commented
Preview looks good on [draft](https://draft-openlibertyio.mybluemix.net/blog/)

![Screen Shot 2022-08-26 at 11 43 28 AM](https://user-images.githubusercontent.com/48686014/187502217-5c452ddf-4258-4f27-aacd-3e5d199a9420.png)

2022-08-30 17:21 UTC, dmuelle commented
preview looks good on [draft](https://draft-openlibertyio.mybluemix.net/blog/)
![Screen Shot 2022-08-30 at 1 19 22 PM](https://user-images.githubusercontent.com/48686014/187502554-b5899424-8e47-4b5e-b37e-3e74783d1131.png)

2022-08-30 17:23 UTC, dmuelle commented
Note that the title of his post is "Guide: How to develop an IBM OpenLiberty Feature"

I've altered that slightly  for our blog roll: "How to develop an Open Liberty user feature"

Before proceeding, just want to make sure that's ok and that we are ok with syndicating something that says "IBM OpenLiberty"

2022-09-06 13:56 UTC, mbroz2 requested changes

2022-09-06 13:56 UTC, mbroz2 commented on blog_tags.json
> +            "posts": ["develop-user-feature.adoc","open-liberty-semeru-performance",
```suggestion
            "posts": ["develop-user-feature","open-liberty-semeru-performance",
```

2022-09-06 13:56 UTC, mbroz2 commented on blog_tags.json
> +            "posts": ["develop-user-feature.adoc","open-liberty-with-cargo-tracker",
```suggestion
            "posts": ["develop-user-feature","open-liberty-with-cargo-tracker",
```

2022-09-06 14:03 UTC, mbroz2 submitted a review, later dismissed
Approved; however, I'll mention that Maven has "user-feature-install" twice (and my personal preference is for spaces after commas)

2022-09-06 14:16 UTC, dmuelle commented
Thanks @mbroz2 - added spaces and removed the redundant tag from the Maven section

2022-09-06 16:15 UTC, ramkumar-k-9286 approved these changes

2022-09-06 16:16 UTC, merged