22.0.0.10 post
OpenLiberty/blogs pull request #2575
Opened 2022-09-21 14:02 UTC by mbroz2

Preview on draft site: https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/09/27/22.0.0.10.html

2022-09-21 17:10 UTC, dmuelle requested changes
ID review

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +1. If the auth filter for a `openidConnectClient` matches the request, choose that configuration.
```suggestion
1. If the authentication filter for a `openidConnectClient` configuration matches the request, choose that configuration.
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +2. Check the issuer from the JWT against the issuers of all config elements. If the issuer from the JWT matches a single `openidConnectClient` configuration element, choose that configuration.
```suggestion
2. Check the issuer claim from the JWT against the `issuer` attributes from of all `openidConnectClient` elements. If the issuer claim from the JWT matches the `issuer` attribute in only one `openidConnectClient` configuration element, choose that configuration.
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +3. If the issuer from the JWT matches the issuer of multiple `openidConnectClient` configuration elements, choose the first configuration matched.
```suggestion
3. If the issuer claim from the JWT matches the `issuer` attribute in multiple `openidConnectClient` configuration elements, choose the first configuration that matches.
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +4. If the issuer does not match the issuer of any configuration elements, choose between all of the config elements in a non-deterministic manner.
```suggestion
4. If the issuer claim from the JWT does not match the `issuer` attribute of any `openidConnectClient` configuration elements, choose one of the configuration elements in a nondeterministic manner.
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +4. If the issuer does not match the issuer of any configuration elements, choose between all of the config elements in a non-deterministic manner.
I feel like it's unclear what happens in the case of "4"- does it validate the request based on other criteria than the issuer? Does it continue checking configs until it finds a valid option, or exhausts the choices?

Maybe more detail than is needed here but something I want to sort out for the docs

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +Starting in 22.0.0.10, the OpenID Connect Client 1.0 feature supports using the issuer claim from the JWT or JWS access token for selecting which `openidConnectClient` configuration to use for a JWT
```suggestion
Starting in 22.0.0.10, the link:{url-prefix}/docs/latest/reference/feature/openidConnectClient-1.0.html[OpenID Connect Client 1.0] feature supports using the issuer claim from the JWT or JWS access token for selecting which `openidConnectClient` configuration to use for a JWT inbound propagation request.  Prior to this release, complicated authentication filters were required if more than one issuer was used for the same resource. Instead, the OpenID Connect Client 1.0 feature can now be configured with simpler `openidConnectClient` elements for each required issuer.
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +For example, for an issuer claim value of `"https://hostname/op1"` and a `server.xml` file configured as follows:
```suggestion
The following `server.xml` file example shows two Open ID connect client configurations, with an link:{url-prefix}/docs/latest/authentication-filters.html[authentication filter] configured to route requests to the `RP2` configuration. If a request with an issuer claim value of `https://hostname/op1` is presented, the `RP1` configuration is selected unless the `rp2filter` applies to the request.
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +The `"RP1"` configuration is selected as long as the `"rp2filter"` does not apply to the request. Therefore, an attempt to find which `openidConnectClient` configuration applies to the request will b
```suggestion
Open Liberty selects the `openidConnectClient` configuration to use for a JWT request according to the following algorithm:
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +For more information about OpenID Connect Client refer to the link:https://openid.net/specs/openid-connect-core-1_0.html[OpenID Connect Client specification].
```suggestion
For more information about OpenID Connect Client, refer to the link:https://openid.net/specs/openid-connect-core-1_0.html[OpenID Connect Client specification].
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +When a JDBC datasource is configured with `validationTimeout` the connection pool should validate a connection before it is passed back to the application. If the connection is invalid (e.g. after a
```suggestion
When a JDBC datasource is configured with `validationTimeout`, the connection pool should validate a connection before it is passed back to the application. If the connection is invalid (e.g. after a database failover event), other connections in the pool should be purged according to the `purgePolicy` configuration. The application should therefore rarely receive an invalid database connection.
```

2022-09-21 17:10 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +However, if the connection manager is configured with `numConnectionsPerThreadLocal=1`, once a connection is stashed as a `ThreadLocal`, it isn't validated before being used by the application result
```suggestion
However, if the connection manager is configured with `numConnectionsPerThreadLocal=1`, once a connection is stashed as a `ThreadLocal`, it isn't validated before being used by the application, which results in a `SQLException`. Also, if the application calls `isValid` on the connection and the connection is determined to be invalid, the connection manager does not apply the `purgePolicy` logic to other connections in the pool, so clients may see multiple errors until each of the worker threads is used. 
```

2022-09-22 15:15 UTC, mbroz2 commented on posts/2022-09-27-22.0.0.10.adoc
> +4. If the issuer does not match the issuer of any configuration elements, choose between all of the config elements in a non-deterministic manner.
The way I read this is that if 1-3 do not apply, then 'randomly' pick any of the openidConnectClient config elements.

@teddyjtorres can you expand on 4.  Is this nondeterministic per request, or is it nondeterministic for the first request, and then that result is applied to all following requests until server restarts (or I suppose until the feature is unloaded and reloaded)?

2022-09-22 17:03 UTC, teddyjtorres commented on posts/2022-09-27-22.0.0.10.adoc
> +4. If the issuer does not match the issuer of any configuration elements, choose between all of the config elements in a non-deterministic manner.
Hi. Yes, it is non-deterministic (as it's always been prior to this change) since we cannot guarantee the order in which config admin will order these configs. It might not be as it appears in the server.xml. We are just stating what it always has been.

2022-09-22 17:10 UTC, teddyjtorres commented on posts/2022-09-27-22.0.0.10.adoc
> +4. If the issuer does not match the issuer of any configuration elements, choose between all of the config elements in a non-deterministic manner.
Therefore, to avoid confusion, the following is proposed, since this is what it always has done,

If the issuer claim from the JWT does not match the `issuer` attribute of any `openidConnectClient` configuration elements, choose the first configuration that matched.

2022-09-22 17:28 UTC, dmuelle commented on posts/2022-09-27-22.0.0.10.adoc
> +4. If the issuer does not match the issuer of any configuration elements, choose between all of the config elements in a non-deterministic manner.
@teddyjtorres - to clarify- what does matched mean in the case of 4?

> If the issuer claim from the JWT _does not match_ the issuer attribute of any openidConnectClient configuration elements, choose the first configuration that _matched_.

For the steps 1-3, "match" seems to mean that the issuer claim from the JWT matches the `issuer` attribute of one or more `openidConnectClient` configuration elements. But for step 4 we are saying `...the issuer claim from the JWT does not match the issuer attribute of any openidConnectClient configuration elements`- so what is it that "matches" in `the first configuration that matched.` ?

2022-09-26 12:56 UTC, teddyjtorres approved these changes

2022-09-27 15:14 UTC, dmuelle approved these changes
LGTM

2022-09-27 15:16 UTC, merged