Staging to prod, publish serverless and performance posts
OpenLiberty/blogs pull request #2656
Opened 2022-10-17 20:12 UTC by dmuelle

#2583 
#2598 

Both posts look good on staging: https://blogs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/?search=performance_enhancements&key=tag

2022-10-17 22:45 UTC, mbroz2 approved these changes

2022-10-17 22:47 UTC, mbroz2 requested changes
for the serverless blog post, we should set the open-graph-image: to point at the ibm-code-engine-active-instances.png

2022-10-18 01:26 UTC, dmuelle commented
PR to add OG image: https://github.com/OpenLiberty/blogs/pull/2658

2022-10-18 01:39 UTC, mbroz2 approved these changes

2022-10-18 01:39 UTC, merged