add the Chinese blog of comparing MP and Spring
OpenLiberty/blogs pull request #2718
Opened 2022-11-07 10:44 UTC by Emily-Jiang

2022-11-07 11:36 UTC, Emily-Jiang commented
I tried to add a few images as well. However, the images was not displayed in the blog. Please take a look to see whether I have done wrong.

2022-11-07 15:34 UTC, dmuelle commented on posts/2022-10-16-microprofile-spring-comparison-in-chinese.adoc
> +image::/img/blog/sspring_starter.png[SpringBoot starter, width=70%,align="center"]
```suggestion
image::/img/blog/spring_starter.png[SpringBoot starter, width=70%,align="center"]
```

2022-11-07 15:38 UTC, dmuelle commented on posts/2022-10-16-microprofile-spring-comparison-in-chinese.adoc
> +image::img/blog/MP_starter.png[MicroProfile Starter, width=70%,align="center"]
```suggestion
image::/img/blog/MP_starter.png[MicroProfile Starter, width=70%,align="center"]
```

2022-11-07 15:40 UTC, dmuelle commented
Hi Emily- I found a couple typos in the image URLs. I fixed them and the images are showing in the PR preview now.

2022-11-07 16:07 UTC, Emily-Jiang commented
Awessome, thanks @dmuelle !

2022-11-14 19:03 UTC, kinueng commented
There are a few things we need to do on the `openliberty.io` website code to support this blog post. I will push this through to production when `openliberty.io` is ready for this PR.

2022-11-14 19:03 UTC, kinueng requested changes
@kinueng and team need to deliver code before this PR can be merged.

This PR is blocked by https://github.com/OpenLiberty/openliberty.io/issues/2931

2022-12-06 18:49 UTC, merged