2675 using codeengine with paketo buildpack for liberty
OpenLiberty/blogs pull request #2736
Opened 2022-11-10 18:18 UTC by kevin-ortega

https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/11/11/using-codeengine-with-paketo-buildpack-for-liberty.html
https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/11/11/using-codeengine-with-paketo-buildpack-for-liberty.html
https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/11/11/using-codeengine-with-paketo-buildpack-for-liberty.html
https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/11/11/using-codeengine-with-paketo-buildpack-for-liberty.html

2022-11-10 18:20 UTC, kevin-ortega commented
#2736 

 @GraceJansen Please review
@dmuelle Can you please review?

2022-11-10 19:38 UTC, kevin-ortega commented
https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2022/11/11/using-codeengine-with-paketo-buildpack-for-liberty.html

2022-11-10 19:43 UTC, kevin-ortega commented
![image](https://user-images.githubusercontent.com/29545669/201190872-c43f70c4-e977-4ae4-9ffe-bfd378a1b1b3.png)
![image](https://user-images.githubusercontent.com/29545669/201191001-cdfd1162-12d8-45d6-beb8-bab41e1c18b9.png)
![image](https://user-images.githubusercontent.com/29545669/201191050-8360e1a7-a0e4-4052-88a9-74ae36c3c4fd.png)
![image](https://user-images.githubusercontent.com/29545669/201191100-fc4df14e-ce11-4dd1-ac0b-cfe53a09eade.png)

2022-11-10 20:35 UTC, hibell submitted a review, later dismissed
LGTM

2022-11-10 21:08 UTC, dmuelle requested changes
ID Review- left some suggestions. 

Generally speaking, it could be helpful to briefly state in the introduction some of the benefits to using this approach. I think the post does a good job of telling you how to do it, but it doesn't say much about why you might want to or in what context it's a helpful strategy.

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +link:https://www.ibm.com/cloud/code-engine[IBM Cloud Code Engine] provides the next level of easy application deployment and mature management of critical business applications in IBM Cloud. Use Code
```suggestion
You can use link:https://www.ibm.com/cloud/code-engine[IBM Cloud Code Engine] to easily deploy Java applications by using the link:https://openliberty.io/blog/2022/04/01/cloud-native-liberty-buildpack.html[Paketo Buildpack for Liberty] with your container images or source code. Code Engine provides the next level of easy application deployment and mature management of critical business applications in IBM Cloud. 
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +The intent of this blog is not a Code Engine tutorial but to provide instructions on how to use the Paketo Buildpack for Liberty with Code Engine.
```suggestion
This post provides instructions on how to use the Paketo Buildpack for Liberty with Code Engine. To learn more about using Code Engine, see link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-getting-started[Getting started with IBM Cloud Code Engine].

With the Paketo Buildpack for Liberty, you can use Open Liberty or WebSphere Liberty to run your application. 
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +To deploy container images you'll also need:
```suggestion
To deploy container images, you'll also need:
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Details on deploying your application from repository source code from the Code Engine console can be found link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-app-source-code#deploy-app-sour
```suggestion
For details on deploying your application from repository source code from the Code Engine console, see  link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-app-source-code#deploy-app-source-code[Deploying your app from repository source code from the console].
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Details on deploying your application from repository source code with the CLI can be found link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-app-source-code#deploy-app-source-code-cli[here
```suggestion
For details on deploying your application from repository source code with the CLI, see  link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-app-source-code#deploy-app-source-code-cli[Deploying your app from repository source code with the CLI].
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Code Engine can build your container from source with link:https://paketo.io[Paketo buildpacks] using the link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-plan-build#build-buildpack-strat[
```suggestion
Code Engine can build your container from source with link:https://paketo.io[Paketo buildpacks] using the link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-plan-build#build-buildpack-strat[Cloud Native Buildpacks] build strategy. The Paketo Buildpack for Liberty is included in the composite Paketo Buildpack for Java that also includes `tomcat` and `tomee` application servers. Tomcat is the default application server and to use Open Liberty requires a little extra configuration. 

You can set the application server that the Paketo Buildpack for Java uses by specifying the `BP_JAVA_APP_SERVER` environment variable. If this variable is undefined, the order of Java application servers in the buildpack dictates which one will be picked. Normally, environment variables are provided to buildpacks by using the `--env` parameter on the `pack build` CLI command. However, Code Engine does not use `pack,` so the environment variables must be provided in a `.buildenv` file in the application's root source directory.  
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Login to the IBM Cloud console and head to the link:https://cloud.ibm.com/codeengine/overview[Code Engine overview] page.  When building from source, enter the url of the respository hosting your sou
```suggestion
Log in to the IBM Cloud console and head to the link:https://cloud.ibm.com/codeengine/overview[Code Engine overview] page.  When you are building from source, enter the URL of the repository that hosts your source and click **Start creating **.
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +On the `Start creating` page it's important to enter `9080` for `Listening port`.
```suggestion
On the **Start creating** page, you must enter `9080` as the value for `Listening port`.
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +We recommend setting the minimum number of instances to `1` in the `Runtime settings` section.
```suggestion
In the **Runtime settings** section, we recommend setting the minimum number of instances to `1`.
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Press `Specify build details`.
```suggestion
Click **Specify build details**. 
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +In this example, the source root is the `finish` directory and contains the `.buildenv` file.
```suggestion
In this example, the source root that contains the`.buildenv` file is the `finish` directory. 
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +On the `Start creating` page it's important to enter `9080` for `Listening port`.
Do we intedn for them to use the sample image? If so, might be helpful to say

"Use the sample image"

or similar so users arent left to wonder what to do with the field

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Press `Next` and select the `Cloud native buildpack` strategy.  Press `Next`.
```suggestion
Click **Next** and select **Cloud Native Buildpack** as the source.  Click **Next**.
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Enter the details of where Code Engine will store your image and press `Done`.
```suggestion
Enter the details of where Code Engine will store your image and click **Done**.
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Enter the details of where Code Engine will store your image and press `Done`.
will the user know what to enter here?

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Press `Create` to have Code Engine create and deploy your application.
```suggestion
Click **Create** to have Code Engine create and deploy your application.  
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +. Create a `.buildenv` file with `BP_JAVA_APP_SERVER=liberty`
```suggestion
. Create a `.buildenv` file that defines the  `BP_JAVA_APP_SERVER=liberty` environment variable.
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> += Other configurations using the `.buildenv` file
```suggestion
== Other environment variables you can set in the `.buildenv` file
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +`BP_LIBERTY_INSTALL_TYPE` link:https://github.com/paketo-buildpacks/liberty#install-types[Install type] of Liberty, Open Liberty (ol) or WebSphere Liberty (wlp).  Open Liberty is the default.
```suggestion
BP_LIBERTY_INSTALL_TYPE::
Specifies the  link:https://github.com/paketo-buildpacks/liberty#install-types[Install type] of Liberty. Possible values are `ol` (Open Liberty) or  `wlp` (WebSphere Liberty).  Open Liberty is the default.
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +`BP_LIBERTY_PROFILE` to specify which liberty profile to install. Valid profiles for Open and WebSphere Liberty are documented link:https://github.com/paketo-buildpacks/liberty#profiles[here].
```suggestion
BP_LIBERTY_PROFILE::
Specifies which liberty profile to install. Valid profiles for Open and WebSphere Liberty are documented link:https://github.com/paketo-buildpacks/liberty#profiles[in the buildpacks documentation].
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +`BP_LIBERTY_FEATURES` a space separated list of Liberty features to be installed with the Liberty runtime. Supports any valid Liberty feature.
```suggestion
BP_LIBERTY_FEATURES::
Specifies a space-separated list of Liberty features to be installed with the Liberty runtime. Supports any valid Liberty feature.
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +Code Engine doesn't use the `pack build` CLI to create container images. It plugs into the cloud native buildpack's lifecycle natively. As a result, some features of the Paketo Buildpack for Liberty
```suggestion
Code Engine doesn't use the `pack build` CLI to create container images. It plugs into the cloud native buildpack's lifecycle natively. As a result, some features of the Paketo Buildpack for Liberty are not easily available to Code Engine. Features like link:https://github.com/paketo-buildpacks/liberty/blob/main/docs/installing-ifixes.md[installing iFixes], link:https://github.com/paketo-buildpacks/liberty#using-custom-features[custom features], and installing from a link:https://github.com/paketo-buildpacks/liberty#building-from-a-packaged-server[packaged server] or link:https://github.com/paketo-buildpacks/liberty#building-from-a-liberty-server[server directory] aren't available when you use Code Engine to create the container image. 

For these features, you can use the `pack build` CLI to create the container image, push the image to an external container registry. Then, use Code Engine to deploy and manage your container by pulling your container image from the container registry from the Code Engine console or CLI.  
```

2022-11-10 21:08 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-deploy-app-crimage[Follow these instructions] to deploy applications from the IBM Cloud Container Registry.
```suggestion
link:https://cloud.ibm.com/docs/codeengine?topic=codeengine-deploy-app-crimage[Follow these instructions] to deploy applications from the IBM Cloud Container Registry with Code Engine. 
```

2022-11-11 18:50 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +open-graph-image: https://openliberty.io/img/twitter_card.jpg
```suggestion
open-graph-image:https://openliberty.io/img/blog/code_engine_build_step_details.png
```

2022-11-11 18:50 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +open-graph-image-alt: Open Liberty Logo
```suggestion
open-graph-image-alt: screen capture of Code Engine build details
```

2022-11-11 18:50 UTC, dmuelle commented on posts/2022-11-11-using-codeengine-with-paketo-buildpack-for-liberty.adoc
> +In this example, the source root that contains the`.buildenv` file is the `finish` directory.
```suggestion
In this example, the source root that contains the `.buildenv` file is the `finish` directory. 
```

2022-11-11 18:51 UTC, dmuelle approved these changes

2022-11-11 18:51 UTC, merged