Blog post for Dec 2022 refresh of Liberty Tools
OpenLiberty/blogs pull request #2802
Opened 2022-12-14 09:35 UTC by yeekangc

Blog post for early release refresh of Liberty Tools.  This is for #2796.

2022-12-14 09:36 UTC, yeekangc commented
Targeting 2022/12/19 for publishing for now.  We can align with the site refresh for 22.0.0.13.  The earliest we can go is 2022/12/16.

2022-12-14 15:49 UTC, yeekangc commented
Cc @natalie-bernhard @kinueng

2022-12-14 17:39 UTC, dmuelle reviewed
ID review- a few suggestions

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +Developers want an intuitive set of tools that allows them to focus on their code, simplifies their iterative coding cycle, supports the APIs they use, takes away mundane manual tasks, gives them fle
```suggestion
Developers need tools  for cloud-native application development that are both intuitive and delightful. Enter Liberty Tools: a set developer tools for the Eclipse IDE, Visual Studio Code, and IntelliJ IDEA development environments.

Liberty Tools can simplify your iterative coding cycle by taking away mundane manual tasks and providing coding support for the APIs you use. They also give you flexibility in your choice of development environment.
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +Developers want an intuitive set of tools that allows them to focus on their code, simplifies their iterative coding cycle, supports the APIs they use, takes away mundane manual tasks, gives them fle
IMO this sentence is trying to do too much- breaking it up improves readability

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +Liberty Tools bring together several capabilities for developers:
```suggestion
Liberty Tools bring together a range of capabilities:
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +* Iterate fast using Liberty dev mode integrated within the IDE: Simply start dev mode then write your code. With dev mode, we do the heavy lifting for you: picking up your code changes, running them
```suggestion
* Iterate fast with Liberty dev mode integrated within your IDE. With dev mode, we do the heavy lifting for you: code changes are automatically detected, recompiled, and deployed whenever you save a new change.
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +* Write code confidently using Jakarta EE and Jakarta EE APIs with assistance (e.g., validations, quick fixes, completions)
```suggestion
* Write code confidently using Jakarta EE and Jakarta EE APIs with assistance such as validations, quick fixes, completions.
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +* Edit Liberty configuration files easily with assistance
```suggestion
* Edit Liberty configuration files easily with assistance.
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +* Build applications to run on Liberty with Maven and Gradle using Liberty Maven and Gradle plugins
```suggestion
* Use the Liberty Maven and Gradle plug-ins to build Liberty applications.
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +Today, we are delighted to share that we are making an early release refresh of the Liberty Tools with a core set of capabilities for building cloud-native applications with Liberty available to Java
```suggestion
Today, we are delighted to share that an early release refresh of the Liberty Tools. This release provides a core set of capabilities for building cloud-native applications with Liberty, including support for Jakarta EE 9.x Web Profile and MicroProfile 3 & 4 APIs.  Try them out:
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +* https://marketplace.eclipse.org/content/liberty-tools[Download] Liberty Tools for Eclipse IDE
```suggestion
* https://marketplace.eclipse.org/content/liberty-tools[Liberty Tools for Eclipse IDE] 
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +* https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[Download] Liberty Tools for Visual Studio Code
```suggestion
* https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[Liberty Tools for Visual Studio Code] 
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +* https://plugins.jetbrains.com/plugin/14856-liberty-tools[Download] Liberty Tools for IntelliJ IDEA
```suggestion
* https://plugins.jetbrains.com/plugin/14856-liberty-tools[Liberty Tools for IntelliJ IDEA] 
```

2022-12-14 17:39 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +We will dive into the tools further in future blog posts.  Please stay tuned.
```suggestion
We will dive into the tools further in future blog posts.  Stay tuned!
```

2022-12-14 17:43 UTC, dmuelle reviewed
a few more comments

2022-12-14 17:43 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> += Fast iterative cloud-native Java application development using Liberty Tools
```suggestion
= Fast iterative cloud-native Java application development with Liberty Tools
```

2022-12-14 17:43 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +seo-title: Fast iterative cloud-native Java application development using Liberty Tools - OpenLiberty.io
```suggestion
seo-title: Fast iterative cloud-native Java application development with Liberty Tools - OpenLiberty.io
```

2022-12-14 17:43 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +seo-description: Liberty Tools enable fast iterative development of cloud-native applications using Jakarta EE & MicroProfile APIs in Eclipse IDE, IntelliJ IDEA, and Visual Studio Code for Java devel
```suggestion
seo-description: Liberty Tools enable fast iterative development of cloud-native applications that use Jakarta EE & MicroProfile APIs in Eclipse IDE, IntelliJ IDEA, and Visual Studio Code for Java developers
```

2022-12-14 17:43 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +blog_description: "Liberty Tools enable fast iterative development of cloud-native applications using Jakarta EE & MicroProfile APIs in Eclipse IDE, IntelliJ IDEA, and Visual Studio Code for Java dev
```suggestion
blog_description: "Liberty Tools enable fast iterative development of cloud-native applications that use Jakarta EE & MicroProfile APIs in Eclipse IDE, IntelliJ IDEA, and Visual Studio Code for Java developers"
```

2022-12-14 17:43 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +title: "Fast iterative cloud-native Java application development using Liberty Tools"
```suggestion
title: "Fast iterative cloud-native Java application development with Liberty Tools"
```

2022-12-15 03:53 UTC, yeekangc commented
Thank you for the review, @dmuelle.  I committed your suggestions and made a few updates.  Can you please take another look?

2022-12-15 18:11 UTC, dmuelle requested changes
replace extra mention of Jakarta with MP

2022-12-15 18:11 UTC, dmuelle commented on posts/2022-12-19-cloud-native-java-development-with-liberty-tools.adoc
> +* Write code confidently using Jakarta EE and Jakarta EE APIs with assistance such as validations, quick fixes, completions.
```suggestion
* Write code confidently using MicroProfile and Jakarta EE APIs with assistance such as validations, quick fixes, completions.
```

2022-12-16 14:48 UTC, dmuelle approved these changes, later dismissed
LGTM- if we are targeting Tuesday to publish, need to change the file name to 
`2022-12-20-cloud-native-java-development-with-liberty-tools.adoc`

2022-12-19 19:42 UTC, dmuelle commented
@yeekangc - @mbroz2 suggested on slack we could add these images of the tools offerings in the 3 marketplaces to make the post more appealing

![lt-ecl](https://user-images.githubusercontent.com/48686014/208506664-d985446e-4c36-4444-b486-5954e0c37592.png)
![lt-intj](https://user-images.githubusercontent.com/48686014/208506666-4d066aba-398c-455e-aeda-bb1e61b69217.png)
![lt-vsc](https://user-images.githubusercontent.com/48686014/208506668-8418ec69-206a-4041-a4f5-811cdc570467.png)

If you don't have a chance to incorporate them when you update the filename, I can add them before we publish. Just don't want to create a conflict in versions since I dont have access to your fork

2022-12-20 14:18 UTC, dmuelle approved these changes
LGTM

2022-12-20 14:18 UTC, merged