Update 2023-02-21-23.0.0.2-beta.adoc
OpenLiberty/blogs pull request #2955
Opened 2023-02-21 20:26 UTC by mbroz2

2023-02-21 21:24 UTC, aknguyen7 reviewed
I did not have appSecurity-4.0 (nor appSecurity-2.0) in my env and it still works. Tested with appSecurity-4.0 & mpOpenApi-3.0 works as well.

2023-02-22 03:20 UTC, mbroz2 commented on posts/2023-02-21-23.0.0.2-beta.adoc
> +Although this example uses the `mpOpenApi-3.0` and `appSecurity-4.0` features, you can use any version of the MicroProfile OpenAPI and Application Security (Jakarta Security) features.
```suggestion
Although this example uses the `mpOpenApi-3.0` and `appSecurity-4.0` features, you can use any valid version combination of the MicroProfile OpenAPI and Application Security (Jakarta Security) features.

```

2023-02-23 16:05 UTC, aknguyen7 requested changes
@mbroz2 i think we should remove the appSecurity feature (if it's still okay to make change), i looked at the docs here https://github.com/OpenLiberty/docs/issues/6228 and it's corrected, we don't have it included, I updated the GA Blog to not include that as well. Thanks

2023-02-27 14:54 UTC, mbroz2 commented on posts/2023-02-21-23.0.0.2-beta.adoc
> +    <feature>appSecurity-4.0</feature>
```suggestion
```

2023-02-27 14:57 UTC, mbroz2 commented on posts/2023-02-21-23.0.0.2-beta.adoc
> +        <feature>appSecurity-4.0</feature>
```suggestion
```

2023-02-27 14:59 UTC, mbroz2 commented on posts/2023-02-21-23.0.0.2-beta.adoc
> +Although this example uses the `mpOpenApi-3.0` and `appSecurity-4.0` features, you can use any valid version combination of the MicroProfile OpenAPI and Application Security (Jakarta Security) featur
```suggestion
Although this example uses the `mpOpenApi-3.0`, you can use any MicroProfile OpenAPI version that is compatible with your other features..

```

2023-02-27 15:00 UTC, mbroz2 commented on posts/2023-02-21-23.0.0.2-beta.adoc
> +
```suggestion
```

2023-02-27 15:00 UTC, mbroz2 commented on posts/2023-02-21-23.0.0.2-beta.adoc
> +Although this example uses the `mpOpenApi-3.0`, you can use any MicroProfile OpenAPI version that is compatible with your other features..
```suggestion
Although this example uses the `mpOpenApi-3.0` feature, you can use any MicroProfile OpenAPI version that is compatible with your other features.

```

2023-02-27 15:55 UTC, dmuelle approved these changes
LGTM

2023-02-27 16:38 UTC, merged