Liberty tools deep dive
OpenLiberty/blogs pull request #2965
Opened 2023-02-24 00:31 UTC by awisniew90

For Issue #2958

2023-02-24 00:31 UTC, awisniew90 commented
Draft PR #2963

Draft site: https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2023/02/20/liberty-tools-eclipse-deep-dive.html

2023-02-24 00:32 UTC, awisniew90 commented
@GraceJansen 

The youtube link does not seem to be rendering.... the asciidoc syntax looks fine on my end, so not sure if it's just a connection issue.

2023-03-06 14:13 UTC, dmuelle requested changes
ID review

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +<iframe width="560" height="315" align="center" src="https://www.youtube.com/watch?v=OcgR_4BL12o" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-
```suggestion
video::OcgR_4BL12o[youtube, width="560", height="315", align="center"]
```

try the[ video macro](https://docs.asciidoctor.org/asciidoc/latest/macros/audio-and-video/#video-macro-syntax) instead

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Liberty Tools for Eclipse IDE provides a simplified yet powerful development experience. With capabilities like dev mode, Liberty config editing, and Jakarta EE and MicroProfile code assistance, you
```suggestion
Liberty Tools for Eclipse IDE provide a simplified yet powerful development experience. With capabilities like dev mode, Liberty config editing, and Jakarta EE and MicroProfile code assistance, you can code and manage your application without leaving your IDE.
```

per [previous discussions](https://github.com/OpenLiberty/docs/issues/5823#issuecomment-1350304447), we are treating "Liberty Tools" as plural.

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Check out the following video for a deep dive walkthrough:
```suggestion
Check out the following video for a deep dive walk-through of Liberty Tools for Eclipse IDE:
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Liberty Tools is the next generation IDE tooling for developing cloud-native Java applications with Liberty. It takes an app-centric approach, leveraging the capabilities of the Liberty Maven and Lib
```suggestion
Liberty Tools are the next generation IDE tooling for developing cloud-native Java applications with Liberty. These tools take an app-centric approach, leveraging the capabilities of the Liberty Maven and Liberty Gradle plugins, so you no longer have to spend time creating and managing Liberty instances. By running dev mode behind the scenes, the Liberty runtime is automatically downloaded and started, and your app is built, packaged and deployed to it. To save even more time, listeners detect any changes you make and your app is automatically rebuilt and redeployed without having to restart the runtime.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Keeping in line with the app-centric design, Liberty Tools provides code assistance for both Jakarta EE and MicroProfile APIs. Code completion, hover descriptions, diagnostics and quick-fixes save ti
```suggestion
Keeping in line with the app-centric design, Liberty Tools provide code assistance for both Jakarta EE and MicroProfile APIs. Code completion, hover descriptions, diagnostics and quick-fixes save time, reduce errors, and keep you focused on your code. Liberty Tools accomplish this by integrating with the link:https://github.com/eclipse/lsp4jakarta[Language Server for Jakarta EE] and the link:https://github.com/eclipse/lsp4mp[Language Server for MicroProfile], both open source projects that are continually adding new features and support.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +While much of the runtime mechanics are automated with Liberty Tools, some runtime configuration is, of course, necessary. However, this process has been streamlined with config assistance for `serve
```suggestion
While much of the runtime mechanics are automated with Liberty Tools, some runtime configuration is, of course, necessary. However, this process is streamlined by configuration assistance for `server.xml`, `bootstrap.properties`, and `server.env` files. Rather than having to refer to the documentation to find the correct Liberty feature to add or the appropriate value to set for your specific logging attribute, Liberty Tools provide lists of options and descriptions, all without leaving Eclipse.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Prefer another IDE? Liberty Tools for Eclipse IDE maintains functional parity with plugins for link:https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[Visual Stud
```suggestion
Prefer another IDE? Liberty Tools for Eclipse IDE maintain functional parity with plugins for link:https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext[Visual Studio Code] and link:https://plugins.jetbrains.com/plugin/14856-liberty-tools/[Intellij IDEA].
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Liberty Tools for Eclipse IDE is designed to work with link:https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/docs/user-guide.md#software-requirements[supported versions] of both
```suggestion
Liberty Tools for Eclipse IDE are designed to work with link:https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/docs/user-guide.md#software-requirements[supported versions] of both 
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Since Liberty Tools uses the Liberty Maven and Liberty Gradle plugins behind the scenes, these plugins must be configured in your application's `pom.xml` or `build.gradle` files. Liberty Tools will a
```suggestion
Since Liberty Tools use the Liberty Maven and Liberty Gradle plugins behind the scenes, these plugins must be configured in your application's `pom.xml` or `build.gradle` files. Liberty Tools also need to run the Maven or Gradle executable, which you can enable by configuring the Maven and Gradle home in the link:https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/docs/user-guide.md#setting-preferences[tool preferences], or by including a wrapper with the application.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Any application in your Eclipse workspace that contains `src/main/liberty/config/server.xml` is automatically enabled to run with Liberty Tools. Actions are available to manage these apps such as `St
```suggestion
Any application in your Eclipse workspace that contains  a `src/main/liberty/config/server.xml` file  is automatically enabled to run with Liberty Tools. Actions are available to manage these apps such as `Start`, `Stop`, `Debug` and `Run Tests`.  You can run these actions from either the Liberty Dashboard or the Eclipse **Run As** menu.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +The Liberty Dashboard consolidates the Liberty enabled applications in your workspace into a single view. To open the dashboard, click on Open Liberty UFO icon on the top tray (or press Alt+L). To ru
```suggestion
The Liberty Dashboard consolidates the Liberty enabled applications in your workspace into a single view. To open the dashboard, click on the Open Liberty UFO icon  or press **Alt+L**. To run an action, simply right click on an app in the list.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Liberty Tools offers the same set of actions in the Eclipse "Run As" menu that appears when you right click on a project in the Project Explorer view.
```suggestion
Liberty Tools offers the same set of actions as the Liberty Dashboard in the Eclipse **Run As** menu that appears when you right-click on a project in the Project Explorer view.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +To start your application in dev mode, select either the `Start` or `Start...` actions. The latter will open a `Run Configurations` dialog box where you can add to the command-line parameters such as
```suggestion
To start your application in dev mode, select either the **Start** or **Start...** actions. The latter opens a `Run Configurations` dialog box where you can add to the command-line parameters such as link:https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#additional-parameters[additional parameters to dev mode] or configure the JRE to use when the app runs. When either start action is selected, Liberty Tools opens a `Terminal` tab and starts dev mode. 
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +NOTE: The `Start in container` action will link:https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#devc-container-mode[start dev mode in a local Docker container] and requires link:https:/
```suggestion
NOTE: The `Start in container` action link:https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#devc-container-mode[starts dev mode in a local Docker container] and requires link:https://github.com/OpenLiberty/liberty-tools-eclipse/blob/main/docs/user-guide.md#docker['docker' on the PATH].
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Tests are important for any application. Liberty Tools makes it easy to run your unit and integration tests by either selecting the `Run tests` action, or simply clicking `Enter` in the terminal. You
```suggestion
Tests are important for any application. Liberty Tools makes it easy to run your unit and integration tests by either selecting the **Run tests** action, or simply clicking **Enter** in the terminal. You can even view the results of your latest run by selecting **View test reports**.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +The Liberty runtime is configured with port 7777 for debugging by default. However, this requires that port to be available on your system and for you to manually attach a debugger. With Liberty Tool
```suggestion
By default, the Liberty runtime is configured with port 7777 for debugging. However, this configuration requires that port to be available on your system and for you to manually attach a debugger. With Liberty Tools, you can start your app using the "Debug" action, which finds an available port and automatically attaches the Eclipse debugger to it. 
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Code completion for Jakarta EE makes it easy to add classes and methods to your app. Just type `CTRL` + `Space` from within any Java file to see a list of available code snippets to choose from. Addi
```suggestion
Code completion for Jakarta EE makes it easy to add classes and methods to your app. Just type **CTRL** + **Space** from within any Java file to choose from a list of available code snippets. Additionally, diagnostics flag errors and suggest quick-fixes to implement on the spot.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Similar code completion is available for MicroProfile as well as type-ahead suggestions and hover descriptions for MicroProfile config properties. You can easily see what values are set for injected
```suggestion
Similar code completion is available for MicroProfile, as well as type-ahead suggestions and hover descriptions for MicroProfile config properties. You can easily see what values are set for injected properties directly from your code and get lists of available variables and values to add to your configuration.
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Liberty Tools streamlines the process of configuring the Liberty runtime through config completion for `server.xml`, `bootstrap.properties` and `server.env` files. Type `CTRL` + `Space` from within t
```suggestion
Liberty Tools streamlines the process of configuring the Liberty runtime through config completion for `server.xml`, `bootstrap.properties` and `server.env` files. Type **CTRL** + **Space** from within these files to get lists of suggested configuration elements, properties, and values. 
```

2023-03-06 14:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Like what you see? Need support? Find us on link:https://app.gitter.im/#/room/#OpenLiberty_developer-experience:gitter.im[gitter], or open an issue or enhancement link:https://github.com/OpenLiberty/
```suggestion
Like what you see? Need support? Find us on link:https://app.gitter.im/#/room/#OpenLiberty_developer-experience:gitter.im[gitter], or open an issue or enhancement link:https://github.com/OpenLiberty/liberty-tools-eclipse/issues[on GitHub].
```

2023-03-07 15:13 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Liberty Tools is the next generation IDE tooling for developing cloud-native Java applications with Liberty. It takes an app-centric approach, leveraging the capabilities of the Liberty Maven and Lib
based on slack discussion, leaving "Liberty Tools" as singular

2023-03-07 19:55 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +Liberty Tools is the next generation IDE tooling for developing cloud-native Java applications with Liberty. It takes an app-centric approach, leveraging the capabilities of the Liberty Maven and Lib
```suggestion
Liberty Tools is the next generation IDE tooling for developing cloud-native Java applications with Liberty. It takes an app-centric approach, leveraging the capabilities of the Liberty Maven and Liberty Gradle plugins, so you no longer have to spend time creating and managing Liberty instances. By running dev mode behind the scenes, the Liberty runtime is automatically downloaded and started, and your app is built, packaged, and deployed to it. To save even more time, listeners detect any changes you make, and your app is automatically rebuilt and redeployed without having to restart the runtime.
```

2023-03-07 19:55 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +While much of the runtime mechanics are automated with Liberty Tools, some runtime configuration is, of course, necessary. However, this process has been streamlined with config assistance for `serve
```suggestion
While much of the runtime mechanics are automated with Liberty Tools, some runtime configuration is, of course, necessary. However, this process has been streamlined with config assistance for `server.xml`, `bootstrap.properties`, and `server.env` files. Rather than having to refer to the documentation to find the correct Liberty feature to add or the appropriate value to set for your specific logging attribute, Liberty Tools provides lists of options and descriptions, all without having to leave Eclipse.
```

2023-03-07 19:59 UTC, dmuelle commented on posts/2023-02-20-liberty-tools-eclipse-deep-dive.adoc
> +By default, the Liberty runtime is configured with port 7777 for debugging. However, this configuration requires that port to be available on your system and for you to manually attach a debugger. Wi
```suggestion
By default, the Liberty runtime is configured with port 7777 for debugging. However, this configuration requires that port to be available on your system and for you to manually attach a debugger. With Liberty Tools, you can start your app using the `Debug` action, which finds an available port and automatically attaches the Eclipse debugger to it. 
```

2023-03-08 14:33 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +Any application in your Eclipse workspace that contains `src/main/liberty/config/server.xml` is automatically enabled to run with Liberty Tools. Actions are available to manage these apps such as `St
```suggestion
Any application in your Eclipse workspace that contains `src/main/liberty/config/server.xml` is automatically enabled to run with Liberty Tools. Actions are available to manage these apps such as `Start`, `Stop`, `Debug` and `Run Tests`, and you can run these actions from either the Liberty Dashboard or the Eclipse **Run As** menu.
```

2023-03-08 14:34 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +The Liberty Dashboard consolidates the Liberty enabled applications in your workspace into a single view. To open the dashboard, click on Open Liberty UFO icon on the top tray (or press Alt+L). To ru
```suggestion
The Liberty Dashboard consolidates the Liberty enabled applications in your workspace into a single view. To open the dashboard, click on the Open Liberty UFO icon on the top tray or press **Alt**+**L**. To run an action, simply right click on an app in the list.
```

2023-03-08 14:35 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +The Liberty Dashboard consolidates the Liberty enabled applications in your workspace into a single view. To open the dashboard, click on the Open Liberty UFO icon on the top tray or press **Alt** +
```suggestion
The Liberty Dashboard consolidates the Liberty enabled applications in your workspace into a single view. To open the dashboard, click on the Open Liberty UFO icon on the top tray or press **Alt** + **L**. To run an action, simply right-click on an app in the list.
```

2023-03-08 14:37 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +Liberty Tools offers the same set of actions in the Eclipse "Run As" menu that appears when you right click on a project in the Project Explorer view.
```suggestion
Liberty Tools offers the same set of actions in the Eclipse **Run As** menu that appears when you right click on a project in the Project Explorer view.
```

2023-03-08 14:37 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +To start your application in dev mode, select either the `Start` or `Start...` actions. The latter will open a `Run Configurations` dialog box where you can add to the command-line parameters such as
```suggestion
To start your application in dev mode, select either the **Start** or **Start...** actions. The latter opens a **Run Configurations** dialog box where you can add to the command-line parameters such as link:https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#additional-parameters[additional parameters to dev mode] or configure the JRE to use when running the app. When a start action is selected, Liberty Tools opens a **Terminal** tab and starts dev mode. 
```

2023-03-08 14:40 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +Tests are important for any application. Liberty Tools makes it easy to run your unit and integration tests by either selecting the `Run tests` action, or simply clicking `Enter` in the terminal. You
```suggestion
Tests are important for any application. Liberty Tools makes it easy to run your unit and integration tests by either selecting the **Run tests** action, or simply clicking **Enter** in the terminal. You can even view the results of your latest run by selecting **View test reports**.
```

2023-03-08 14:40 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +
Liberty Tools provides coding assistance for Jakarta EE and MicroProfile APIs, as well as select Liberty configuration files.

2023-03-08 14:41 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +
```suggestion
Liberty Tools provides coding assistance for Jakarta EE and MicroProfile APIs, as well as select Liberty configuration files.

```

2023-03-08 14:42 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +Similar code completion is available for MicroProfile, as well as type-ahead suggestions and hover descriptions for MicroProfile config properties. You can easily see what values are set for injected
```suggestion
Similar code completion is available for MicroProfile, as well as type-ahead suggestions and hover descriptions for MicroProfile Config properties. You can easily see what values are set for injected properties directly from your code and get lists of available variables and values to add to your configuration.
```

2023-03-08 14:43 UTC, dmuelle commented on posts/2023-03-08-liberty-tools-eclipse-deep-dive.adoc
> +Like what you see? Need support? Find us on link:https://app.gitter.im/#/room/#OpenLiberty_developer-experience:gitter.im[gitter], or open an issue or enhancement link:https://github.com/OpenLiberty/
```suggestion
Like what you see? Need support? Find us on link:https://app.gitter.im/#/room/#OpenLiberty_developer-experience:gitter.im[Gitter], or open an issue or enhancement link:https://github.com/OpenLiberty/liberty-tools-eclipse/issues[on Github].
```

2023-03-08 14:44 UTC, dmuelle approved these changes
LGTM thanks

2023-03-08 14:46 UTC, merged