Jakub's certification post
OpenLiberty/blogs pull request #3476
Opened 2023-12-13 14:16 UTC by lauracowen

2023-12-13 15:47 UTC, dmuelle requested changes
minor edits- mainly to remove "above"

2023-12-13 15:47 UTC, dmuelle commented on posts/2023-12-15-liberty-certification.adoc
> +The 60 link:/guides/[cloud-native developer guides] help you to get hands-on with the technologies and tools that are available to use with Open Liberty. The guides are a great way for you to refresh
```suggestion
The 60 link:/guides/[cloud-native developer guides] give you hands-on experience with the technologies and tools that you can use with Open Liberty. The guides are a great way for you to refresh your knowledge about a technology or to discover new ones. They range in complexity, from link:/guides/getting-started.html[Getting started with Open Liberty] and link:/guides/rest-intro.html[Creating a RESTful web service] to topics such as link:/guides/microprofile-metrics.html[Providing metrics from a microservice], and link:/guides/social-media-login.html[Authenticating users through social media providers].
```

2023-12-13 15:47 UTC, dmuelle commented on posts/2023-12-15-liberty-certification.adoc
> +By using the above resources, and your own knowledge and experience of writing cloud-native Java applications, you're ready to try the Liberty certification exam - good luck! Read more about the cert
```suggestion
By using these resources, and your own knowledge and experience of writing cloud-native Java applications, you're ready to try the Liberty certification exam - good luck! Read more about the certification on the link:https://www.ibm.com/training/certification/C9004800[IBM Training portal].
```

2023-12-15 12:18 UTC, yeekangc approved these changes
LGTM

2023-12-15 12:22 UTC, merged