2024-03-12 Argocd drift blog pt 1
OpenLiberty/blogs pull request #3667
Opened 2024-03-27 14:29 UTC by danielguinan1

PR for part1 of blog in this issue: #3012

2024-03-28 16:06 UTC, dmuelle requested changes
ID review

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +title: "Configuration drift: Why its bad and how to solve it with GitOps and ArgoCD"
```suggestion
title: "Configuration drift: Why it's bad and how to solve it with GitOps and ArgoCD"
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +seo-description: Configuration drift can complicate deployments and jeopardize the stability of production environments. Find out how to solve configuration drift with the use of GitOps and ArgoCD.
```suggestion
seo-description: Configuration drift can complicate deployments and jeopardize the stability of production environments. Find out how to solve configuration drift by using GitOps and ArgoCD.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +blog_description: "Configuration drift can complicate deployments and jeopardize the stability of production environments. Find out how to solve configuration drift with the use of GitOps and ArgoCD.
```suggestion
blog_description: "Configuration drift can complicate deployments and jeopardize the stability of production environments. Find out how to solve configuration drift by using GitOps and ArgoCD."
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> += Configuration drift: Why its bad and how to solve it with GitOps and ArgoCD
```suggestion
= Configuration drift: Why it's bad and how to solve it with GitOps and ArgoCD
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +In today's modern software ecosystem, despite many organizations embracing Continuous Integration and Continuous Deployment (CI/CD) methodologies, they still grapple with the persistent issue of conf
```suggestion
Configuration drift refers to the disparity between configurations as coded in repositories like Git and what's actively deployed. Despite  embracing Continuous Integration and Continuous Deployment (CI/CD) methodologies, modern software organizations still grapple with this disparity, which not only complicates deployments but can also jeopardize the stability of production environments. 
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +As an example... imagine a scenario where a Continuous Deployment (CD) pipeline deploys an application to a Kubernetes cluster, with all configurations codified in a Git repository. Just like that sh
```suggestion
For example, imagine a scenario where a Continuous Deployment (CD) pipeline deploys an application to a Kubernetes cluster, with all configurations codified in a Git repository, as shown in the following diagram:
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +Everything operates seamlessly. As time progresses, as shown in the next image, changes and updates are made to the application, these changes are committed to the Git repository and pushed to the de
```suggestion
Everything operates seamlessly. In the next image, developers make changes and updates to the application. They commit these changes to the Git repository and push to the deployed application, updating our app in production. All good so far.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +However, a team member identifies a performance issue and, aiming for a quick fix, uses a kubectl command to directly tweak the resource allocations for a specific deployment. In this case, they've g
```suggestion
However, a team member identifies a performance issue and, aiming for a quick fix, uses a `kubectl` command to directly tweak the resource allocations for a specific deployment. In this case, they've gone straight to the production deployment! 
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +Although this might resolve the immediate problem, the cluster's state now diverges from what's documented in Git.
```suggestion
Although this fix might resolve the immediate problem, the cluster's state now diverges from what's documented in Git.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +As many organizations will use the same Git Repo for configuring Dev, Staging and Prod Kubernetes clusters, the above changes to only one cluster (in this case, Prod) will cause drift between Dev, St
```suggestion
As many organizations use the same Git repo to configure dev, staging and prod Kubernetes clusters, changes to only one cluster (in this case, prod) cause drift between the clusters. 
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +This scenario describes an example of configuration drift and how this can easily occur within your own cloud-native applications.
```suggestion
This scenario describes an example of configuration drift and how easily it can occur within your own cloud-native applications.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +The consequences of configuration drift can vary in severity from mildly inconvenient to extremely serious and business threatening. However, no matter the severity, configuration drift will result i
```suggestion
The consequences of configuration drift can vary in severity from mildly inconvenient to extremely serious and business threatening. However, no matter the severity, configuration drift will result in liabilities and negative impacts upon your app, team and business.  
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +In the best case scenario, configuration drift can cause:
```suggestion
At the very least, configuration drift can cause:
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +* Additional work for the team
```suggestion
* Extra work for the team
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +* Significant security vulnerabilities due to unpatched vulnerabilities or absent security protocols leading to cyberattacks and breaches
```suggestion
* Significant security vulnerabilities due to unpatched vulnerabilities or absent security protocols that lead to cyberattacks and breaches
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +The difficulty with configuration drift, is that the longer you leave these problems and the larger the differences in configuration, the worse these problems become, rapidly! If you allow many indiv
```suggestion
The difficulty with configuration drift is that the longer you leave these problems and the larger the differences in configuration, the worse these problems become, rapidly! If you allow many individual misconfigurations to pile up over time without addressing them, they will quickly compound together, resulting in configuration drift that once could have been an easy fix becoming a significant, major problem.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +In the majority of cases, like the example at the start of this blog, configuration drift isn't intentional. Typically, the most comment cause of configuration drift is ad hoc manual changes by devel
```suggestion
Typically, the most common causes of configuration drift are ad hoc manual changes by developers or admins, like the scenario we explored at the start of this post. However, other potential causes can include: 
* Software patches that alter system configurations
* Software or hardware updates that conflict with existing configurations 
* Poor communication: For example, if one team does not inform other teams about a setting modification.
* Poor documentation: If config changes are not effectively documented, team members might not know how to properly configure systems. 
* Human error, such as typos and other incorrect attributes.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +So as you can see, there are many reasons why configuration drift happens. But, in essence, regardless of how it happens, configuration drift occurs when code changes get through without being monito
```suggestion
As you can see, there are many reasons why configuration drift happens. But regardless of how it happens, configuration drift occurs when code changes get through without being monitored or approved.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +What can make this even worse is the potential for developers to create even more configuration drift trying to solve issues quickly that are caused by configuration drift. As they try to fix these p
```suggestion
What can make this even worse is the potential for developers to create even more configuration drift while trying to solve issues that are caused by configuration drift. As they try to fix these problems, more code changes get pushed without proper review, monitoring, tracking, or reporting, which leads to even further inconsistency between the desired configurations and actual state. This vicious cycle can continue to snowball, creating more and more drift and more serious problems!
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +In order to solve configuration drift, we must reconcile any potential configuration differences and ensure consistency across our deployments.
```suggestion
To solve configuration drift, we must reconcile any potential configuration differences and ensure consistency across our deployments.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +To do this, we can use **GitOps** — a principle that revolves around using Git as the single source of truth for declarative infrastructure and applications. GitOps is a framework designed to streaml
```suggestion
To do this, we can use **GitOps**,  using Git as the single source of truth for declarative infrastructure and applications. GitOps is a framework that streamlines and optimizes how operations and infrastructure are handled in the modern cloud-native landscape. GitOps revolves around four core principles: 
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +. Declarative configuration
```suggestion
Declarative configuration::
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> ++
```suggestion
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +
```suggestion
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +. Versioned and immutable source of truth
```suggestion
Versioned and immutable source of truth::
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +
```suggestion
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> ++
```suggestion
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +. Automated delivery
```suggestion
Automated delivery::
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +
```suggestion
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> ++
```suggestion
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +. Continuously reconciled
```suggestion
Continuously reconciled::
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +
```suggestion
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> ++
```suggestion
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +ArgoCD is a declarative, GitOps continuous delivery tool for Kubernetes. It works by ensuring that a Kubernetes cluster's state matches the configurations defined in a Git repository. It facilitates
```suggestion
link:https://argo-cd.readthedocs.io/en/stable[ArgoCD] is a declarative, GitOps continuous delivery tool for Kubernetes. It works by ensuring that a Kubernetes cluster's state matches the configurations defined in a Git repository. It facilitates the automatic deployment and synchronization of applications to the desired environments.  
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +Integrating this into the application we explored at the start of this blog, you'll see ArgoCD added into our pipeline, ensuring that our cluster remains in sync with what is defined in our Git repos
```suggestion
To take the example application we explored at the start of this post, you'll see ArgoCD added into our pipeline, ensuring that our cluster remains in sync with what is defined in our Git repository.
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +== How can we make use of GitOps and ArgoCD? ==
```suggestion
== How can we get started with ArgoCD and GitOps?  
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +If you’d like to see how you can practically use GitOps principles and ArgoCD to deploy Open Liberty applications, we've provided a detailed tutorial style blog which follows on from this introductor
```suggestion
If you’d like to see how you can practically use GitOps principles and ArgoCD to deploy Open Liberty applications, we've provided a detailed tutorial that follows on from this introductory post. This step-by-step tutorial walks through  how to take an existing Open Liberty application and introduce ArgoCD to help solve configuration drift in your own applications.  
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +== Summary and Next Steps ==
```suggestion
== Summary and next steps
```

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +== What is configuration drift? ==
I think you can lose this section- drift is already defined at the top of the post and demonstrated in the subsequent example

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +== Summary and Next Steps ==
this section doesn't add much, I'd consider cutting it as the previous section sums things up and provides a call to action

2024-03-28 16:06 UTC, dmuelle commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +If you’d like to see how you can practically use GitOps principles and ArgoCD to deploy Open Liberty applications, we've provided a detailed tutorial style blog which follows on from this introductor
shouldn't there be a link to the next post here?

2024-04-05 10:11 UTC, gljrobinson commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +Check out the next blog in this series to explore how to apply this learning to your own applications.
```suggestion
```

2024-04-05 10:11 UTC, gljrobinson commented on posts/2024-03-12-argocd-drift-pt1.adoc
> +
```suggestion
```

2024-04-25 17:46 UTC, dmuelle approved these changes

2024-04-25 17:46 UTC, merged