Update Database SSL primer with updates to Oracle JDBC 23
OpenLiberty/blogs pull request #3872
Opened 2024-07-12 15:26 UTC by KyleAure

- Oracle JDBC 23 no longer requires osdt_core and osdt_cert dependencies for Oracle Wallet support

2024-07-12 16:27 UTC, dmuelle reviewed
ID review

2024-07-12 16:27 UTC, dmuelle commented on posts/2021-06-04-database-ssl-primer.adoc
> +> NOTE: prior to Oracle JDBC 23 the Oracle PKI driver (oraclepki.jar) depended on osdt_core.jar and osdt_cert.jar for Oracle Wallet support. After Oracle JDBC 23 the Oracle PKI driver includes these
```suggestion
> NOTE: prior to Oracle JDBC 23 the Oracle PKI driver (`oraclepki.jar`) depended on the `osdt_core.jar` and `osdt_cert.jar` files for Oracle Wallet support. After Oracle JDBC 23, the Oracle PKI driver includes these dependencies and the files are no longer required.
```

2024-07-12 16:27 UTC, dmuelle commented on posts/2021-06-04-database-ssl-primer.adoc
> +> NOTE: prior to Oracle JDBC 23 the Oracle PKI driver (oraclepki.jar) depended on osdt_core.jar and osdt_cert.jar for Oracle Wallet support. After Oracle JDBC 23 the Oracle PKI driver includes these
not sure ive got the end part right, but as written it seemed a little confusing- if they are no longer required, why does the driver include them?

2024-07-12 20:52 UTC, KyleAure commented
@dmuelle I added some clarification: [`4eafa25` (#3872)](https://github.com/OpenLiberty/blogs/pull/3872/commits/4eafa25fceea27581a0f3cf685bdf6635a1ab548)

2024-07-23 19:26 UTC, dmuelle requested changes
minor edits- sorry for the delay

2024-07-23 19:26 UTC, dmuelle commented on posts/2021-06-04-database-ssl-primer.adoc
> +> NOTE: prior to Oracle JDBC 23 the Oracle PKI driver (`oraclepki.jar`) depended on the `osdt_core.jar` and `osdt_cert.jar` files for Oracle Wallet support. After Oracle JDBC 23, the Oracle PKI drive
```suggestion
> NOTE: prior to Oracle JDBC 23, the Oracle PKI driver (`oraclepki.jar`) depended on the `osdt_core.jar` and `osdt_cert.jar` files for Oracle Wallet support. After Oracle JDBC 23, the Oracle PKI driver includes the functionality that was previously provided by `osdt_core.jar` and `osdt_cert.jar` and therefore these files are no longer required.
```

2024-07-23 20:55 UTC, KyleAure commented
@dmuelle  No worries.  Committed your suggestion.

2024-07-24 14:13 UTC, dmuelle approved these changes

2024-07-24 14:13 UTC, merged

2024-07-24 14:14 UTC, dmuelle commented
Approved and merged. @KyleAure -please also commit these recent updates from your fork back to the `draft` branch if you haven't already to keep the file in sync