Grace3003 keycloak
OpenLiberty/blogs pull request #3899
Opened 2024-07-25 10:43 UTC by GraceJansen

2024-07-30 16:16 UTC, dmuelle requested changes
ID review

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +As our infrastructure has evolved and cloud-native technologies and platforms have become ever more popular, we've begun to truly understand the vital importance of properly securing our application
```suggestion
As our infrastructure evolves and cloud-native technologies and platforms become ever more popular, we're beginning to truly understand the importance of staking a security-first approach when building enterprise, cloud-native Java applications. This need was especially clear in the chaos after the link:https://www.ibm.com/topics/log4shell[Log4Shell vunerability]. The importance of security is highlighted in many cloud-native application methodologies, including the link:https://developer.ibm.com/articles/15-factor-applications/[15-factor app methodology], where the additional factor of "Authentication and authorization" was added to the original link:https://developer.ibm.com/articles/creating-a-12-factor-application-with-open-liberty/[12 factor app methodology]. 
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +So, we know it's important... but that doesn't help us understand how we can practicaly apply this and make sure that we have effectively secured our own applications. That's what we aim to show in t
```suggestion
So, we know it's important... but how we can practically apply this and make sure that we effectively secure our own applications? That's what we aim to show in this post: demonstrating how an application running on Liberty that uses Jakarta EE and MicroProfile open source standards , can utilise tools like Keycloak to ensure the application is protected and secure.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +link:https://www.keycloak.org/[Keycloak] is an open source Identity and Access Management (IAM) tool, offering authentication and authorisation for applications. Being an IAM tool, it helps to stream
```suggestion
link:https://www.keycloak.org/[Keycloak] is an open source Identity and Access Management (IAM) tool, offering authentication and authorisation for applications. It helps to streamline the authentication process, removing the need for developers to worry about storing or authenticating users. Authentication ensures that the right individuals have appropriate access to resources. This is becoming ever more important as more data becomes protected and we become responsible for ensuring there is no unauthorized access to protected or private data.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +Keycloak provides important and useful capabilities such as: Single Sign-On (SSO), user federation, strong authentication, user management, fine-grained authorization, and more. Keycloak was original
```suggestion
Keycloak provides important and useful capabilities such as single sign-on (SSO), user federation, strong authentication, user management, fine-grained authorization, and more. Keycloak was originally created by RedHat and is now used for Red Hat's SSO. It is an enterprise-level tool and so is well suited to enterprise applications and enterprise-focused tools and standards, such as Liberty, MicroProfile and Jakarta EE.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +Open Liberty can easily integrate with Keycloak, which can be used as an OpenID Connect Provider, using Jakarta Security and MicroProfile JWT. link:https://jakarta.ee/specifications/security/[Jakarta
```suggestion
Open Liberty can easily integrate with Keycloak, which can be used as an OpenID Connect Provider, by using Jakarta Security and MicroProfile JWT. link:https://jakarta.ee/specifications/security/[Jakarta Security] defines a standard for creating secure Jakarta EE applications in modern application paradigms. link:{url-prefix}/docs/latest/reference/feature/mpJwt-1.1.html[MicroProfile JSON Web Token] is a specification that defines the use of JWT as a bearer token in a microservices request to authenticate users. A JSON Web Token (JWT) is a self-contained token that is designed to securely transmit information as a JSON object. The information in this JSON object is digitally signed and can be trusted and verified by the recipient. If you'd like to learn more about this specification, check out our interactive, hands-on Open Liberty guide: link:https://openliberty.io/guides/microprofile-jwt.html[Securing microservices with JSON Web Tokens].
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +We'll demonstrate how integrating an Open Liberty application with Keycloak can be achieved by showing how access tokens can be obtained from Keycloak using Jakarta Security and then how access token
```suggestion
We'll demonstrate how to integrate an Open Liberty application with Keycloak by showing how to obtain access tokens from Keycloak using Jakarta Security. We then show how access tokens can be consumed from Keycloak by using MicroProfile JWT.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +__Tips before you dive into the demos:__
```suggestion
== Before you begin
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +__Note that when using Keycloak, terms like 'realm' and 'client' are used. A 'realm' is a space where you manage objects, including users, applications, roles, and groups. A 'client' is an entity tha
```suggestion
Keycloak uses the terms _realm_ and _client_. A _realm_ is a space where you manage objects, including users, applications, roles, and groups. A _client_ is an entity that can request Keycloak to authenticate a user.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +In this blog post, a Keycloak server has been setup with a realm called `openliberty` which contains a client called `sample-openliberty-keycloak` and the realm roles of `admin` and `user`. Additiona
```suggestion
In this blog post, the following prerequisites are set:

* A Keycloak server is set up with a realm called `openliberty`, which contains a client called `sample-openliberty-keycloak` and the realm roles of `admin` and `user`. 
* Client authentication is enabled for the sample-openliberty-keycloak` client.
* `http://localhost:9090/Callback` is added as a valid redirect URI.
* The `microprofile-jwt` client scope is set to `Default`.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +This example shows how the `@OpenIdAuthenticationMechanismDefinition` can be configured to setup an authentication flow with Keycloak.
```suggestion
This example shows how to configure the  `@OpenIdAuthenticationMechanismDefinition` annotation to set up an authentication flow with Keycloak.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +Now, with this annotation set up, your REST endpoints can be protected using the `@RolesAllowed` annotation which will trigger the authentication flow when a user tries to access the endpoint.
```suggestion
Now, with this annotation set up, your REST endpoints can be protected using the `@RolesAllowed` annotation, which triggers the authentication flow when a user tries to access the endpoint.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +The example code below shows a JAX-RS resource which contains a `/username` endpoint which is only accessible by users with the `admin` role and an `/os` endpoint which is accessible by both users wi
```suggestion
The following example code shows a JAX-RS resource that contains a `/username` endpoint, which is only accessible by users with the `admin` role, and an `/os` endpoint, which is accessible by users with either the `admin` or `user` role.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +Once the requests to these endpoints are authenticated and authorized, the endpoint can now use the access token of the authenticated user.
```suggestion
After the requests to these endpoints are authenticated and authorized, the endpoint can use the access token of the authenticated user.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +Below is an example of the link:https://openliberty.io/docs/latest/microprofile-config-properties.html#jwt[MicroProfile Config properties] required to validate an access token issued by the `openlibe
```suggestion
The following example shows the link:https://openliberty.io/docs/latest/microprofile-config-properties.html#jwt[MicroProfile Config properties] that are required to validate an access token issued by the `openliberty` realm in Keycloak.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +In this example, the `mp.jwt.verify.issuer` is the endpoint of the `openliberty` realm and the `mp.jwt.verify.publickey.location` is the JSON Web Key Sets (JWKS) endpoint of the `openliberty` realm.
```suggestion
In this example, the `mp.jwt.verify.issuer` is the endpoint of the `openliberty` realm and the `mp.jwt.verify.publickey.location` is the JSON Web Key Sets (JWKS) endpoint of the `openliberty` realm. By adding these configuration properties to our application, MicroProfile JWT is now set up to validate access tokens issued by the `openliberty` realm sent as bearer tokens to resources protected using the `@RolesAllowed` annotation.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +
```suggestion
[#obtain]
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +Just as we did in the previous section of this blog (obtaining an acess token using Jakarta Security), we've provided an example below to show a JAX-RS resource which contains a `/username` endpoint
```suggestion
Just as we did in the <<obtain,previous section of this post>>, the following example shows a JAX-RS resource that contains a `/username` endpoint only accessible by users with the `admin` role and an `/os` endpoint accessible by both users with the `admin` or the `user` role. However, this example expects an access token to be included in the request header as a bearer token, whereas the previous section's example starts a new authentication flow to get an access token.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +Once the requests to these endpoints are authenticated and authorized, the endpoint returns information about the system properties.
```suggestion
After the requests to these endpoints are authenticated and authorized, the endpoint returns information about the system properties.
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +This blogpost has emphasised the importance of effective security for our cloud-native Java applications to ensure they are protected. To enable this, we focused on authentication and authorization,
```suggestion
This post emphasises the importance of effective security for our cloud-native Java applications. To secure an application, we focused on authentication and authorization, demonstrating how easy it is how to protect your applications using Jakarta Security, MicroProfile JWT, and Keycloak!
```

2024-07-30 16:16 UTC, dmuelle commented on posts/2024-07-30-keycloak-with-openliberty.adoc
> +If you're interested in checking out full sample application, it is available on GitHub here: link:https://github.com/OpenLiberty/sample-keycloak[https://github.com/OpenLiberty/sample-keycloak].
```suggestion
If you're interested, check out the  https://github.com/OpenLiberty/sample-keycloak[full sample application].
```

2024-07-31 09:59 UTC, gljrobinson commented
I have made these changes in my branch and have merged a PR to draft. Thank you for your review @dmuelle. I believe all of this has now been resolved.

2024-07-31 17:33 UTC, dmuelle approved these changes
LGTM

2024-07-31 17:33 UTC, merged