add zero migration blog and images
OpenLiberty/blogs pull request #4055
Opened 2024-09-25 03:45 UTC by mbroz2

Post for https://github.com/OpenLiberty/blogs/issues/1671

https://blogs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2024/09/30/zero-migration.html

![image](https://github.com/user-attachments/assets/080d8af4-da5d-4999-a390-fd62e5e4ec60)

2024-10-02 09:29 UTC, GraceJansen submitted a review, later dismissed
Looks great to me, thanks Michal

2024-10-02 13:41 UTC, mbroz2 commented
@lauracowen @GraceJansen the blog is currently dated for 9/30.  What date would you like for the publication?

2024-10-03 16:03 UTC, dmuelle requested changes
a few minor  suggestions- can we target after the beta blog publishes on tuesday? The tags file has some changes that have yet to make it to prod.

2024-10-03 16:03 UTC, dmuelle commented on posts/2024-09-30-zero-migration.adoc
> +In today's production environments it is not only expected, but critical, to keep your technology stack as up-to-date as possible. This helps to mitigate security risks, while also benefiting from bu
```suggestion
In today's production environments, it is not only expected, but critical to keep your technology stack as up to date as possible. Staying current helps to mitigate security risks, while also benefiting from bug fixes, performance improvements, and new features and function that can help drive your business's success. This is true whether you're deploying to a cloud or locally, and applies regardless of the deployment type, whether container images, VMs, or bare metal.
```

2024-10-03 16:03 UTC, dmuelle commented on posts/2024-09-30-zero-migration.adoc
> +## The challenge of keeping microservices up-to-date
```suggestion
## The challenge of keeping microservices up to date
```

weird rule, but you generally only hyphenate compound adjectives when the precede the noun they modify, not when they follow it, as here.

2024-10-03 16:03 UTC, dmuelle commented on posts/2024-09-30-zero-migration.adoc
> +This is where the benefit of Liberty's zero-migration architecture comes in. Zero migration is a core design principal of the Liberty application runtime which seeks to make updating Liberty quick an
```suggestion
This is where the benefit of Liberty's zero-migration architecture comes in. Zero migration is a core design principal of the Liberty application runtime that seeks to make updating Liberty quick and easy.
```

2024-10-03 16:03 UTC, dmuelle commented on posts/2024-09-30-zero-migration.adoc
> +You can upgrade the version of Liberty on which your application runs (e.g. to get a security update) without upgrading the versions of the features that the application uses. Whenever a breaking cha
```suggestion
You can upgrade the version of Liberty on which your application runs (e.g. to get a security update) without upgrading the versions of the features that the application uses. Whenever a breaking change needs to be introduced into a feature, its feature version is incremented, but Liberty continues to support all previous versions as well as the new version. This means that you control if and when you want your application to use a newer version of the feature.
```

2024-10-03 16:03 UTC, dmuelle commented on posts/2024-09-30-zero-migration.adoc
> +## Upgrading to a new version of Liberty
```suggestion
## Updating to a new version of Liberty
```

2024-10-03 16:03 UTC, dmuelle commented on posts/2024-09-30-zero-migration.adoc
> +|                          | All releases | Releases ending in “.3”, “.6”, “.9” or “.12”
```suggestion
| Support status                       | All releases | Releases ending in “.3”, “.6”, “.9” or “.12”
```

not sure this is the best heading but the table will fail accessibility with an empty header cell

2024-10-03 16:03 UTC, dmuelle commented on posts/2024-09-30-zero-migration.adoc
> +- Security fixes: Whenever performing a security hardening or patching, we try to maintain the existing behavior of Liberty, configuration, or features. When this is not possible, we work to limit th
```suggestion
- Security fixes: Whenever we perform a security hardening or patching, we try to maintain the existing behavior of Liberty, configuration, or features. When this is not possible, we work to limit the scope of the change to only what is needed to address the security concern.
```

2024-10-03 16:03 UTC, dmuelle commented on posts/2024-09-30-zero-migration.adoc
> +Zero migration not only reduces your technical debt, the overhead, of keeping a runtime current, but in many cases eliminates it entirely, allowing you to focus on the higher value items of developme
```suggestion
Zero migration not only reduces your technical debt, the overhead of keeping a runtime current, but in many cases eliminates it entirely, allowing you to focus on the higher value items of development and operations.
```

2024-10-09 13:35 UTC, dmuelle approved these changes

2024-10-09 13:35 UTC, merged