Add splunk blog
OpenLiberty/blogs pull request #432
Opened 2020-05-26 19:17 UTC by pgunapal

https://draft-openlibertyio.mybluemix.net/blog/2020/05/27/how-to-analyze-open-liberty-logs-with-splunk.html

2020-05-26 19:20 UTC, dmuelle approved these changes
LGTM

2020-05-27 14:46 UTC, mbroz2 requested changes

2020-05-27 14:46 UTC, mbroz2 commented on blog_tags.json
> +            "posts": ["how-to-analyze-open-liberty-logs-with-splunk", "docker-open-liberty-raspberry-pi", "scala-open-liberty-kubernetes",
tags for posts are 1-2 per line; add a newline after your splunk post

2020-05-27 14:53 UTC, pgunapal commented on blog_tags.json
> +            "posts": ["how-to-analyze-open-liberty-logs-with-splunk", "docker-open-liberty-raspberry-pi", "scala-open-liberty-kubernetes",
Done!

2020-05-27 14:54 UTC, merged