Blog for Log Forwarding API
OpenLiberty/blogs pull request #652
Opened 2020-08-17 02:29 UTC by leemelim

2020-08-17 02:29 UTC, leemelim commented
Blog post preview available here: http://elf1.fyre.ibm.com:4000/blog/2020/08/16/ocp-log-forwarding.html

2020-08-18 02:00 UTC, donbourne requested changes

2020-08-18 02:00 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +blog_description: Using Log Forwarding API, you can send logs from Open Liberty deployed in OpenShift Container Platform to remote destinations. Logs, which get collected by cluster logging in OpenSh
- would it make sense to call it the Fluentd forward protocol?  not sure people will know what "forward" protocol is on its own

2020-08-18 02:00 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +seo-title: Forwarding Open Liberty logs to external cluster using OCP Log Forwarding API - OpenLiberty.io
in a few places you refer simply to "external cluster".  it makes me wonder what it's an external cluster of.

2020-08-18 02:00 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Container orchestration system is highly distributed and its parts are dynamic. It becomes difficult to detect which worker nodes are running your containers and pods for your application. Applicatio
Openshift -> OpenShift

2020-08-18 02:00 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Container orchestration system is highly distributed and its parts are dynamic. It becomes difficult to detect which worker nodes are running your containers and pods for your application. Applicatio
Should write an intro paragraph that relates to the problem that you think your users are having.  Maybe they are new to OpenShift and while they can see it has built in Elasticsearch support they are already using Splunk to monitor apps outside of their k8s environment and they'd like to send all their logs to one place to make it easier to manage and to see possible event correlations.  They might wish they could hijack the Fluentd in cluster logging to send logs externally instead...

2020-08-18 02:00 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +[root@ocp ~]# oc -n openshift-logging get cm fluentd -o json | jq -r '.data."fluent.conf"' > fluentd-with-logfowarding.conf
would be good to explain this command a bit so reader knows what it's doing

2020-08-18 02:00 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +== Splunk configuration on external cluster
should probably add some intro in this section to say that the idea is that you're going to set up splunk in an external openshift cluster.  Also good to give credit to the person whose git repo you're sending people off to use for the splunk setup.

2020-08-18 02:00 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +== External Elasticsearch and Kibana configuration
Good here to also introduce what this setup is going to give you.  in this case, looks like you're going to stand up elasticsearch and kibana using docker compose.  say why you chose that, even if it's just a handy way to set it up.

2020-08-18 02:00 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Application logging is one of the fundamental types of observability. It helps you monitor and find the problems on your servers easily. Using Log Forwarding API, you can use existing external enterp
Both applications allow you to aggregate and analyze your Open Liberty log events on OpenShift Cluster Platform
->
Both log analysis solutions allow you to aggregate and analyze log events from Open Liberty servers running on OpenShift Cluster Platform...

2020-08-19 21:33 UTC, donbourne requested changes

2020-08-19 21:33 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Container orchestration system is highly distributed and its parts are dynamic. It becomes difficult to detect which worker nodes are running your containers and pods for your application. Applicatio
First sentence needs to draw me in.  The usual refrains of "distributed systems make debugging hard" are somewhat overdone, so you need to clearly start with what it is someone is really going to want to read this blog for -- in the first sentence.

2020-08-19 21:33 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Container orchestration system is highly distributed and its parts are dynamic. It becomes difficult to detect which worker nodes are running your containers and pods for your application. Applicatio
need to mention, near the beginning, that the Log Fowarding API is a tech preview.

2020-08-19 21:33 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Using `forward` output, you can forward OpenShift Container Platform logs to Splunk using Fluentd forward protocol. You can setup Splunk inside your OpenShift Cluster or on your external machine.
as discussed, refactor this section to make the external splunk scenario be your primary one and refer to the RH article for the splunk in OpenShift one.

2020-08-19 21:33 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +This option sets up Splunk manually on your external machine. If you already have Splunk deployed on your external machine, this option will help you setup the connection between your OpenShift clust
should mention here that this docker compose way of doing setup is really for demo purposes

2020-08-19 21:33 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +This option sets up Splunk manually on your external machine. If you already have Splunk deployed on your external machine, this option will help you setup the connection between your OpenShift clust
also would be good to educate reader on the fact that Fluentd forward forwards to another Fluentd instance, which is why you need it in front of your external Splunk

2020-08-19 21:33 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Using `elasticsearch` output, you can forward logs to Elasticsearch cluster deployed on your external machine. You run Elasticsearch and Kibana with docker compose. This way, obtaining docker images,
mention that the docker compose approach to setting up elasticsearch and kibana is just for demo purposes

2020-08-19 21:33 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Application logging is one of the fundamental types of observability. It helps you monitor and find the problems on your servers easily. Using Log Forwarding API, you can use existing external enterp
"it helps you monitor" - the term "monitor" is generally used in this space to talk about gathering the metrics or logs from a server, so may be confusing the way you're using it here.

2020-08-19 21:33 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Application logging is one of the fundamental types of observability. It helps you monitor and find the problems on your servers easily. Using Log Forwarding API, you can use existing external enterp
We have now seen two popular log collection solutions: Splunk and Kibana. Both log analysis solutions allow you to aggregate and analyze log events from Open Liberty servers running on OpenShift Cluster Platform. 
->
We have now seen two popular log collection solutions - one based on Fluentd / Splunk and the other based on Fluentd / Elasticsearch / Kibana. Both log analysis solutions allow you to aggregate and analyze log events from Open Liberty servers running on OpenShift Cluster Platform.

2020-08-20 17:48 UTC, donbourne submitted a review, later dismissed

2020-08-21 13:35 UTC, donbourne submitted a review, later dismissed

2020-08-21 13:36 UTC, donbourne commented
plan is to do a test run through this before publishing.

2020-08-21 13:47 UTC, donbourne commented
remember to merge PR https://github.com/WASdev/sample.dashboards/pull/18 after this blog is published (the corresponding splunk dashboard)

2020-09-15 22:02 UTC, donbourne approved these changes, later dismissed

2020-10-15 19:18 UTC, Channyboy commented
@lauracowen 
Hi Laura, there have been updates made to this blog.
Can you review the new updates.

2020-10-15 19:41 UTC, lauracowen commented
@Channyboy Can you get someone in your team to review it and then merge/build it on draft? We'll review/edit it after that. Anyone can review it so that you can merge. Thanks

2020-10-19 19:44 UTC, fmhwong submitted a review, later dismissed
`log-forwarding.png` doesn't seem to be used in the doc.

2020-10-19 19:59 UTC, fmhwong approved these changes
LGTM

2020-10-20 16:20 UTC, merged

2020-10-20 22:03 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +OpenShift Container Platform provides a log aggregation solution with cluster logging using Elasticsearch, Fluentd, and Kibana (EFK stack). In addition to EFK stack, integration with other logging ap
In addition to EFK stack, integration with other logging applications has been made available
->
In addition to EFK stack, you can integrate with other log analysis solutions

2020-10-20 22:03 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +Splunk is one of the most popular logging solutions. If you already have Splunk deployed on your external machine, or if you want to start using Splunk as your new logging solution, you will have to
Splunk is one of the most popular logging solutions. 
->
Splunk is one of the most popular log analysis solutions.

2020-10-20 22:03 UTC, donbourne commented on posts/2020-08-16-ocp-log-forwarding.adoc
> +. Ensure your cluster logging instance is created and all pods are fully operational. See the installation and configuration guide for cluster logging: link:https://docs.openshift.com/container-platf
RedHat 
-> 
Red Hat